import {BarraAcciones} from '../../../directives/barraAcciones/barraAcciones';
import {avisarAplicacion,confirmarAplicacion} from '../../../core/interaccion/dialogos.service';
import { Component, OnInit } from '@angular/core'; import { CommonModule } from '@angular/common'; import { FormsModule } from '@angular/forms'; import { ActivatedRoute, Router } from '@angular/router';
import { Sidebar } from '../../../components/sidebar/sidebar'; import { Supbar } from '../../../components/supbar/supbar'; import { Tabla } from '../../../components/tabla/tabla'; import { CatalogoTerritorialService } from '../../../services/catalogo-territorial.service'; import { ContextoSesionService } from '../../../core/session/contexto-sesion.service'; import { Pais,Provincia,Municipio,CodigoPostal } from '../../../interfaces/catalogo-territorial.interface';
type Tipo='paises'|'provincias'|'municipios'|'codigos-postales'|'vias';
@Component({selector:'catalogo-territorial',standalone:true,imports:[CommonModule,FormsModule,Sidebar,Supbar,Tabla,BarraAcciones],templateUrl:'./catalogoTerritorial.html',styleUrl:'../../../styles/estiloGeneral.css'})
export class CatalogoTerritorialPage implements OnInit {
 tipo:Tipo='paises'; titulo=''; vistaActiva:'tabla'|'registro'='tabla'; modo:'insertar'|'modificar'='insertar'; datos:any[]=[]; seleccionado:any=null; registro:any={}; columnas:string[]=[]; titulosColumnas:any={}; paises:Pais[]=[];provincias:Provincia[]=[];municipios:Municipio[]=[];codigos:CodigoPostal[]=[];
 readonly tiposVia=['Calle','Avenida','Plaza','Paseo','Camino','Carretera','Travesía','Urbanización','Polígono','Otro'];
 constructor(private route:ActivatedRoute,private router:Router,private service:CatalogoTerritorialService,private sesion:ContextoSesionService){}
 ngOnInit(){this.route.data.subscribe(d=>{this.tipo=d['catalogo'];this.configurar();this.cargarDependencias();this.consultar();});}
 configurar(){const c:any={paises:['PAÍSES',['empId','paiId','paiCod','paiNom','paiUsuMov','paiFecMov','paiAct']],provincias:['PROVINCIAS',['empId','prvId','paiId','prvCod','prvNom','prvUsuMov','prvFecMov','prvAct']],municipios:['MUNICIPIOS',['empId','munId','prvId','munCod','munNom','munUsuMov','munFecMov','munAct']], 'codigos-postales':['CÓDIGOS POSTALES',['empId','copId','munId','copCod','copUsuMov','copFecMov','copAct']],vias:['VÍAS',['empId','viaId','viaTip','viaCod','viaNom','copId','viaUsuMov','viaFecMov','viaAct']]};this.titulo=c[this.tipo][0];this.columnas=c[this.tipo][1];this.titulosColumnas={empId:'Empresa',paiId:'Id País',paiCod:'Código',paiNom:'País',prvId:'Id Provincia',prvCod:'Código',prvNom:'Provincia',munId:'Id Municipio',munCod:'Código',munNom:'Municipio',copId:'Id C.P.',copCod:'Código Postal',viaId:'Id Vía',viaTip:'Tipo de vía',viaCod:'Código',viaNom:'Vía',paiUsuMov:'Usuario',prvUsuMov:'Usuario',munUsuMov:'Usuario',copUsuMov:'Usuario',viaUsuMov:'Usuario',paiFecMov:'Fecha',prvFecMov:'Fecha',munFecMov:'Fecha',copFecMov:'Fecha',viaFecMov:'Fecha',paiAct:'Activo',prvAct:'Activo',munAct:'Activo',copAct:'Activo',viaAct:'Activo'};}
 cargarDependencias(){this.service.paises().subscribe(v=>this.paises=v.filter(x=>x.paiAct));this.service.provincias().subscribe(v=>this.provincias=v.filter(x=>x.prvAct));this.service.municipios().subscribe(v=>this.municipios=v.filter(x=>x.munAct));this.service.codigos().subscribe(v=>this.codigos=v.filter(x=>x.copAct));}
 consultar(){this.vistaActiva='tabla';this.seleccionado=null;this.service.consultar(this.tipo).subscribe({next:v=>this.datos=v,error:e=>this.error(e)});}
 insertar(){this.modo='insertar';this.registro=this.vacio();this.vistaActiva='registro';} modificar(){if(!this.seleccionado)return;this.modo='modificar';this.registro={...this.seleccionado};this.vistaActiva='registro';}
 guardar(){if(!this.valido())return;const id=this.id();const op=this.modo==='insertar'?this.service.guardar(this.tipo,this.registro):this.service.actualizar(this.tipo,id,this.registro);op.subscribe({next:()=>{this.cargarDependencias();this.consultar();},error:e=>this.error(e)});}
 async eliminar(){if(!this.seleccionado||!await confirmarAplicacion('¿Desea eliminar el registro seleccionado?',true))return;this.service.eliminar(this.tipo,this.id(this.seleccionado)).subscribe({next:()=>{this.cargarDependencias();this.consultar();},error:e=>this.error(e)});}
 cancelar(){this.consultar();} volver(){this.router.navigate(['/territorio']);}
 private id(v=this.registro){return v.paiId||v.prvId||v.munId||v.copId||v.viaId;}
 private valido(){let ok=true;if(this.tipo==='paises')ok=!!this.registro.paiCod?.trim()&&!!this.registro.paiNom?.trim();if(this.tipo==='provincias')ok=!!this.registro.paiId&&!!this.registro.prvCod?.trim()&&!!this.registro.prvNom?.trim();if(this.tipo==='municipios')ok=!!this.registro.prvId&&!!this.registro.munCod?.trim()&&!!this.registro.munNom?.trim();if(this.tipo==='codigos-postales')ok=!!this.registro.munId&&!!this.registro.copCod?.trim();if(this.tipo==='vias')ok=!!this.registro.copId&&!!this.registro.viaTip&&!!this.registro.viaCod?.trim()&&!!this.registro.viaNom?.trim();if(!ok)avisarAplicacion('Complete todos los campos obligatorios.');return ok;}
 private vacio(){const b:any={empId:this.sesion.empresaId};if(this.tipo==='paises')return{...b,paiId:0,paiCod:'',paiNom:'',paiUsuMov:this.sesion.usuarioNombre,paiFecMov:'',paiAct:true};if(this.tipo==='provincias')return{...b,prvId:0,paiId:0,prvCod:'',prvNom:'',prvUsuMov:this.sesion.usuarioNombre,prvFecMov:'',prvAct:true};if(this.tipo==='municipios')return{...b,munId:0,prvId:0,munCod:'',munNom:'',munUsuMov:this.sesion.usuarioNombre,munFecMov:'',munAct:true};if(this.tipo==='codigos-postales')return{...b,copId:0,munId:0,copCod:'',copUsuMov:this.sesion.usuarioNombre,copFecMov:'',copAct:true};return{...b,viaId:0,copId:0,viaTip:'',viaCod:'',viaNom:'',viaUsuMov:this.sesion.usuarioNombre,viaFecMov:'',viaAct:true};}
 private error(e:any){console.error(e);avisarAplicacion(e?.error?.message||'No se pudo completar la operación.');}
}
