import {avisarAplicacion,confirmarAplicacion} from '../../core/interaccion/dialogos.service';
import { CommonModule } from '@angular/common';import { Component,Input,OnChanges,SimpleChanges } from '@angular/core';import { FormsModule } from '@angular/forms';import { AgendaService } from '../../services/agenda.service';import { EstadoReserva,ExcepcionAgenda,HorarioAgenda,RecursoAgenda,ReservaAgenda,TipoRecursoAgenda } from '../../interfaces/agenda.interface';
import { ConfiguracionAgenda } from '../configuracionAgenda/configuracionAgenda';
export type VistaAgenda='dia'|'semana'|'mes';type EstadoCelda='DISPONIBLE'|'OCUPADO'|'PREPARACION'|'LIMPIEZA'|'NO_DISPONIBLE';interface DiaMes{fecha:Date;perteneceAlMes:boolean;}interface FranjaHorario{inicio:string;fin:string;}interface DiaHorario{dia:number;nombre:string;activo:boolean;franjas:FranjaHorario[];}interface CeldaAgenda{fecha:Date;inicio:number;fin:number;estado:EstadoCelda;reservas:ReservaAgenda[];detalle:string;}
@Component({selector:'agendaRegistros',standalone:true,imports:[CommonModule,FormsModule,ConfiguracionAgenda],templateUrl:'./agendaRegistros.html',styleUrls:['./agendaRegistros.css','./agendaHorario.css']})
export class AgendaRegistros implements OnChanges{
 @Input()titulo='Agenda';@Input()tipoRecurso:TipoRecursoAgenda='EMPLEADO';@Input()referenciaId=0;@Input()nombreRecurso='';@Input()intervaloMinutos=5;
 vista:VistaAgenda='semana';zoomMinutos:5|15|30|60=30;panel:'calendario'|'configuracion'|'reserva'='calendario';fechaActual=this.inicioDia(new Date());recurso:RecursoAgenda|null=null;reservas:ReservaAgenda[]=[];excepciones:ExcepcionAgenda[]=[];cargando=false;mensaje='';seleccionada:ReservaAgenda|null=null;celdaSeleccionada:CeldaAgenda|null=null;
 diasHorario:DiaHorario[]=['Lunes','Martes','Miércoles','Jueves','Viernes','Sábado','Domingo'].map((nombre,i)=>({dia:i+1,nombre,activo:i<5,franjas:[{inicio:'09:00',fin:'14:00'}]}));
 excepcion:ExcepcionAgenda={exrFec:this.fechaLocal(new Date()),exrIni:null,exrFin:null,exrDis:false,exrCap:null,exrMot:''};
 nueva={fecha:this.fechaLocal(new Date()),inicio:'09:00',fin:'09:30',titulo:'',observaciones:''};
 get tramosDia(){const inicio=this.recurso?.ragHorVis?this.minutos(this.recurso.ragHorVis):480;return Array.from({length:Math.ceil((1440-inicio)/this.zoomMinutos)},(_,i)=>{const minutos=inicio+i*this.zoomMinutos;return{minutos,etiqueta:`${String(Math.floor(minutos/60)).padStart(2,'0')}:${String(minutos%60).padStart(2,'0')}`};});}
 constructor(private service:AgendaService){}
 ngOnChanges(c:SimpleChanges){if((c['referenciaId']||c['tipoRecurso'])&&this.referenciaId)this.inicializar();}
 inicializar(){this.cargando=true;this.service.recursos().subscribe({next:rs=>{this.recurso=rs.find(r=>r.ragTip===this.tipoRecurso&&r.ragRefId===this.referenciaId)||null;if(this.recurso)this.cargarTodo();else this.crearRecurso();},error:e=>this.error(e)});}
 crearRecurso(){this.service.guardarRecurso({ragTip:this.tipoRecurso,ragRefId:this.referenciaId,ragNom:this.nombreRecurso,ragCap:1,ragMarPre:0,ragMarPos:0,ragHorVis:'08:00'}).subscribe({next:r=>{this.recurso=r;this.cargarTodo();},error:e=>this.error(e)});}
 cargarTodo(){this.cargando=false;this.cargarPeriodo();this.cargarConfiguracion();}
 configuracionGuardada(){this.panel='calendario';this.mensaje='Configuración guardada.';this.cargarTodo();}
 cargarPeriodo(){if(!this.recurso)return;const d=this.limitesPeriodo();this.service.reservas(this.fechaHora(d.desde),this.fechaHora(d.hasta)).subscribe({next:rs=>this.reservas=rs.filter(r=>r.ragId===this.recurso!.ragId),error:e=>this.error(e)});}
 cargarConfiguracion(){if(!this.recurso)return;this.service.horarios(this.recurso.ragId).subscribe({next:h=>this.aplicarHorarios(h),error:e=>this.error(e)});const hoy=new Date(),hasta=new Date(hoy);hasta.setFullYear(hasta.getFullYear()+1);this.service.excepciones(this.recurso.ragId,this.fechaLocal(hoy),this.fechaLocal(hasta)).subscribe({next:e=>this.excepciones=e,error:e=>this.error(e)});}
 aplicarHorarios(h:HorarioAgenda[]){this.diasHorario.forEach(d=>{const f=h.filter(x=>x.horDia===d.dia);d.activo=!!f.length;d.franjas=f.length?f.map(x=>({inicio:x.horIni.slice(0,5),fin:x.horFin.slice(0,5)})):[{inicio:'09:00',fin:'14:00'}];});}
 guardarExcepcion(){if(!this.recurso)return;this.service.guardarExcepcion(this.recurso.ragId,this.excepcion).subscribe({next:()=>{this.excepcion={exrFec:this.fechaLocal(new Date()),exrIni:null,exrFin:null,exrDis:false,exrCap:null,exrMot:''};this.cargarConfiguracion();},error:e=>this.error(e)});}
 async eliminarExcepcion(e:ExcepcionAgenda){if(!e.exrId||!await confirmarAplicacion('¿Eliminar esta excepción?',true))return;this.service.eliminarExcepcion(e.exrId).subscribe({next:()=>this.cargarConfiguracion(),error:x=>this.error(x)});}
 crearReserva(){if(!this.recurso)return;const ini=`${this.nueva.fecha}T${this.nueva.inicio}:00`,fin=`${this.nueva.fecha}T${this.nueva.fin}:00`;this.service.reservar({perId:null,dovId:null,comId:null,resIni:ini,resFin:fin,resTit:this.nueva.titulo,resObs:this.nueva.observaciones,ragId:this.recurso.ragId,tareas:[]}).subscribe({next:()=>{this.panel='calendario';this.nueva={fecha:this.nueva.fecha,inicio:'09:00',fin:'09:30',titulo:'',observaciones:''};this.cargarPeriodo();},error:e=>this.error(e)});}
 cambiarEstado(r:ReservaAgenda,estado:EstadoReserva){this.service.estado(r.resId,estado).subscribe({next:x=>{this.seleccionada=x;this.cargarPeriodo();},error:e=>this.error(e)});}
 reprogramar(r:ReservaAgenda){const fecha=prompt('Nueva fecha (AAAA-MM-DD)',r.resIni.slice(0,10));if(!fecha)return;const inicio=prompt('Nueva hora de inicio (HH:mm)',r.resIni.slice(11,16));if(!inicio)return;const fin=prompt('Nueva hora de fin (HH:mm)',r.resFin.slice(11,16));if(!fin)return;const motivo=prompt('Motivo de la reprogramación','')||'';this.service.reprogramar(r.resId,`${fecha}T${inicio}:00`,`${fecha}T${fin}:00`,motivo).subscribe({next:()=>this.cargarPeriodo(),error:e=>this.error(e)});}
 seleccionarVista(v:VistaAgenda){this.vista=v;this.cargarPeriodo();}hoy(){this.fechaActual=this.inicioDia(new Date());this.cargarPeriodo();}mover(dir:-1|1){const f=new Date(this.fechaActual);if(this.vista==='dia')f.setDate(f.getDate()+dir);if(this.vista==='semana')f.setDate(f.getDate()+7*dir);if(this.vista==='mes')f.setMonth(f.getMonth()+dir);this.fechaActual=f;this.cargarPeriodo();}
 eventosDia(f:Date){const dia=this.fechaLocal(f);return this.reservas.filter(r=>r.resIni.slice(0,10)===dia);}
 franjasDia(f:Date){const diaSemana=f.getDay()===0?7:f.getDay();return this.diasHorario.find(d=>d.dia===diaSemana&&d.activo)?.franjas||[];}
 horarioDia(f:Date){const franjas=this.franjasDia(f);return franjas.length?franjas.map(x=>`${x.inicio}–${x.fin}`).join(' / '):'No disponible';}
 tramoDisponible(f:Date,inicio:number){const fin=inicio+this.zoomMinutos,fecha=this.fechaLocal(f),ex=this.excepciones.filter(e=>e.exrFec===fecha);if(ex.some(e=>!e.exrDis&&this.solapaTramo(e,inicio,fin)))return false;if(ex.some(e=>e.exrDis&&this.cubreTramo(e,inicio,fin)))return true;return this.franjasDia(f).some(x=>inicio>=this.minutos(x.inicio)&&fin<=this.minutos(x.fin));}
 tramoPreparacion(f:Date,inicio:number){if(!this.recurso?.ragMarPre)return false;const franjas=this.franjasDia(f);if(!franjas.length)return false;const apertura=Math.min(...franjas.map(x=>this.minutos(x.inicio)));return inicio<apertura+this.recurso.ragMarPre&&inicio+this.zoomMinutos>apertura;}
 tramoLimpieza(f:Date,inicio:number){if(!this.recurso?.ragMarPos)return false;const franjas=this.franjasDia(f);if(!franjas.length)return false;const cierre=Math.max(...franjas.map(x=>this.minutos(x.fin)));return inicio<cierre&&inicio+this.zoomMinutos>cierre-this.recurso.ragMarPos;}
 tramoOcupado(f:Date,inicio:number){return this.reservasTramo(f,inicio).length>0;}
 reservasTramo(f:Date,inicio:number){const fin=inicio+this.zoomMinutos;return this.eventosDia(f).filter(r=>r.resEst!=='CANCELADA'&&r.resEst!=='AUSENCIA'&&this.minutos(r.resIni.slice(11,16))<fin&&this.minutos(r.resFin.slice(11,16))>inicio);}
 mostrarReservaEnTramo(r:ReservaAgenda,inicio:number){return this.minutos(r.resIni.slice(11,16))>=inicio&&this.minutos(r.resIni.slice(11,16))<inicio+this.zoomMinutos;}
 seleccionarCelda(f:Date,inicio:number){const reservas=this.reservasTramo(f,inicio),fin=inicio+this.zoomMinutos;let estado:EstadoCelda='NO_DISPONIBLE',detalle='Fuera del horario configurado.';if(this.tramoPreparacion(f,inicio)){estado='PREPARACION';detalle=`Tiempo de preparación al inicio del horario (${this.recurso?.ragMarPre||0} min).`;}else if(this.tramoLimpieza(f,inicio)){estado='LIMPIEZA';detalle=`Tiempo de limpieza al final del horario (${this.recurso?.ragMarPos||0} min).`;}else if(reservas.length){estado='OCUPADO';detalle=reservas.length===1?'Tramo ocupado por una reserva.':`Tramo ocupado por ${reservas.length} reservas.`;}else if(this.tramoDisponible(f,inicio)){estado='DISPONIBLE';detalle='Tramo disponible para una nueva reserva.';}else{const ex=this.excepciones.find(e=>e.exrFec===this.fechaLocal(f)&&!e.exrDis&&this.solapaTramo(e,inicio,fin));if(ex)detalle=ex.exrMot?`No disponible: ${ex.exrMot}`:'No disponible por una excepción del calendario.';}this.celdaSeleccionada={fecha:new Date(f),inicio,fin,estado,reservas,detalle};this.seleccionada=reservas[0]||null;}
 celdaActiva(f:Date,inicio:number){return !!this.celdaSeleccionada&&this.fechaLocal(this.celdaSeleccionada.fecha)===this.fechaLocal(f)&&this.celdaSeleccionada.inicio===inicio;}
 etiquetaMinutos(v:number){const n=Math.max(0,Math.min(v,1440));return `${String(Math.floor(n/60)%24).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;}
 etiquetaEstado(e:EstadoCelda){return{DISPONIBLE:'Disponible',OCUPADO:'Ocupado',PREPARACION:'Preparación',LIMPIEZA:'Limpieza',NO_DISPONIBLE:'No disponible'}[e];}
 etiquetaFechaCelda(f:Date){return this.formatear(f,{weekday:'long',day:'numeric',month:'long'});}
 get tituloPeriodo(){if(this.vista==='dia')return this.formatear(this.fechaActual,{weekday:'long',day:'numeric',month:'long',year:'numeric'});if(this.vista==='mes')return this.formatear(this.fechaActual,{month:'long',year:'numeric'});const d=this.diasSemana;return `${this.formatear(d[0],{day:'numeric',month:'short'})} — ${this.formatear(d[6],{day:'numeric',month:'short',year:'numeric'})}`;}
 get diasSemana(){const l=new Date(this.fechaActual);l.setDate(l.getDate()-(l.getDay()||7)+1);return Array.from({length:7},(_,i)=>{const f=new Date(l);f.setDate(l.getDate()+i);return f;});}get diasMes(){const p=new Date(this.fechaActual.getFullYear(),this.fechaActual.getMonth(),1),i=new Date(p);i.setDate(p.getDate()-((p.getDay()||7)-1));return Array.from({length:42},(_,n)=>{const f=new Date(i);f.setDate(i.getDate()+n);return{fecha:f,perteneceAlMes:f.getMonth()===this.fechaActual.getMonth()}as DiaMes;});}
 esHoy(f:Date){return f.toDateString()===new Date().toDateString();}etiquetaDia(f:Date){return this.formatear(f,{weekday:'short',day:'numeric'});}numeroDia(f:Date){return f.getDate();}hora(r:ReservaAgenda){return `${r.resIni.slice(11,16)}–${r.resFin.slice(11,16)}`;}
 private limitesPeriodo(){let desde:Date,hasta:Date;if(this.vista==='dia'){desde=new Date(this.fechaActual);hasta=new Date(desde);hasta.setDate(hasta.getDate()+1);}else if(this.vista==='semana'){desde=this.diasSemana[0];hasta=new Date(desde);hasta.setDate(hasta.getDate()+7);}else{desde=new Date(this.fechaActual.getFullYear(),this.fechaActual.getMonth(),1);hasta=new Date(this.fechaActual.getFullYear(),this.fechaActual.getMonth()+1,1);}return{desde,hasta};}
 private inicioDia(f:Date){return new Date(f.getFullYear(),f.getMonth(),f.getDate());}private fechaLocal(f:Date){return `${f.getFullYear()}-${String(f.getMonth()+1).padStart(2,'0')}-${String(f.getDate()).padStart(2,'0')}`;}private fechaHora(f:Date){return `${this.fechaLocal(f)}T${String(f.getHours()).padStart(2,'0')}:${String(f.getMinutes()).padStart(2,'0')}:00`;}private formatear(f:Date,o:Intl.DateTimeFormatOptions){const t=new Intl.DateTimeFormat('es-ES',o).format(f);return t.charAt(0).toUpperCase()+t.slice(1);}private error(e:any){this.cargando=false;console.error(e);this.mensaje=e?.error?.mensaje||e?.error?.message||e?.error?.detail||'No se pudo completar la operación.';}
 private minutos(hora:string){const[h,m]=hora.split(':').map(Number);return h*60+m;}private solapaTramo(e:ExcepcionAgenda,inicio:number,fin:number){return e.exrIni===null||this.minutos(e.exrIni)<fin&&this.minutos(e.exrFin!)>inicio;}private cubreTramo(e:ExcepcionAgenda,inicio:number,fin:number){return e.exrIni===null||inicio>=this.minutos(e.exrIni)&&fin<=this.minutos(e.exrFin!);}
}
