export interface OpcionMenu{texto:string;ruta?:string}export interface GrupoMenu{id:string;texto:string;opciones:OpcionMenu[]}export interface MenuModulo{titulo:string;grupos:GrupoMenu[]}
const g=(id:string,texto:string,...opciones:(string|[string,string])[]):GrupoMenu=>({id,texto,opciones:opciones.map(o=>typeof o==='string'?{texto:o}:{texto:o[0],ruta:o[1]})});
export const MENUS_MODULOS:Record<string,MenuModulo>={
 administracion:{titulo:'Administración',grupos:[g('menu1','Seguridad',['Usuarios','usuarios'],['Perfiles','perfiles'],['Empresas','empresas'],'Auditoría'),g('menu2','Estructura Organizativa',['Áreas Organizativas','areasOrganizativas'],['Personal de Área','personalArea']),g('menu3','Parametrización',['Parámetros','parametros'],'Selectores','Submenú'),g('menu4','Utilidades','Submenú 1','Submenú 2',['Parámetros','parametros'])]},
 territorio:{titulo:'Territorio',grupos:[g('menu1','Estructura Territorial',['Domicilios','domicilios'],['Vías','vias'],['Códigos Postales','codigosPostales'],['Municipios','municipios'],['Provincias','provincias'],['Países','paises']),g('menu2','Gestión del Territorio',['Gestión de Domicilios','gestionDomicilios'],'Submenú 2','Submenú 3'),g('menu3','Procesos Masivos','Submenú 1','Submenú 2','Submenú 3'),g('menu4','Utilidades','Submenú 1','Submenú 2',['Parámetros','parametros'])]},
 personas:{titulo:'Personas',grupos:[g('menu1','Personas',['Personas','personas'],['Representantes','representantes'],['Domicilios de Notificación','domiciliosNotificacion'],['Domiciliaciones Bancarias','domiciliacionesBancarias']),g('menu2','Gestión de Personas',['Gestión de Personas','gestionPersonas'],'Gestión de Notificaciones','Submenú'),g('menu3','Procesos Masivos','Submenú 1','Submenú 2','Submenú 3'),g('menu4','Utilidades','Submenú 1','Submenú 2',['Parámetros','parametros'])]},
 productos:{titulo:'Productos',grupos:[g('menu1','Productos',['Productos','productos'],['Tipos de Producto','tiposProducto'],'Submenú'),g('menu2','Gestión de Productos',['Gestión de Productos','gestionProductos'],['Gestión de Catálogo','catalogo'],'Submenú 2','Submenú 3'),g('menu3','Procesos Masivos','Submenú 1','Submenú 2','Submenú 3'),g('menu4','Utilidades','Submenú 2',['Parámetros','parametros'])]},
 servicios:{titulo:'Servicios',grupos:[g('menu1','Servicios',['Servicios','servicios'],['Tipos de Servicio','tiposServicio']),g('menu2','Gestión de Servicios',['Gestión de Servicios','gestionServicios'],['Gestión de Catálogo','catalogo']),g('menu3','Procesos Masivos'),g('menu4','Utilidades',['Parámetros','parametros'])]},
 ventas:{titulo:'Ventas',grupos:[g('menu1','Ventas',['Táctil','tactil'],['Pedidos','pedidos'],['Albaranes','albaranes'],['Facturas','ventas'],['Presupuestos','presupuestos']),g('menu2','Gestión de Ventas',['Gestión de Pedidos','gestionPedidos'],['Gestión de Albaranes','gestionAlbaranes'],['Gestión de Facturas','gestionFacturas'],['Gestión de Presupuestos','gestionPresupuestos']),g('menu3','Procesos Masivos','Submenú 1','Submenú 2','Submenú 3'),g('menu4','Utilidades','Submenú 1','Submenú 2',['Parámetros','parametros'])]},
 comunicaciones:{titulo:'Comunicaciones',grupos:[g('menu1','Operación',['Bandeja de Entrada','bandeja'],['Conversaciones','conversaciones'],['Pendientes de Revisión','pendientes']),g('menu2','Gestión',['Gestión de Contactos de Canal','contactosSinIdentificar']),g('menu3','Configuración','Canales',['Parámetros','parametros'])]},
 recursos:{titulo:'Recursos',grupos:[g('menu1','Recursos',['Registro de Recursos','recursos']),g('menu2','Gestión de Recursos',['Gestión de Recursos','gestionRecursos'],['Gestión de Agendas','gestionAgendas']),g('menu4','Utilidades',['Parámetros','parametros'])]},
 caja:{titulo:'Caja',grupos:[g('menu1','Caja',['Registro de Cajas','cajas']),g('menu2','Gestión de Caja',['Gestión de Caja','gestionCaja']),g('menu4','Utilidades',['Parámetros','parametros'])]},
 compras:{titulo:'Compras',grupos:[g('menu1','Compras',['Compras','personas'],'Facturas','Albaranes','Pedidos','Presupuestos','Proveedores'),g('menu2','Gestión de Compras','Gestión de Compras','Submenú 2','Submenú 3'),g('menu3','Procesos Masivos','Submenú 1','Submenú 2','Submenú 3'),g('menu4','Utilidades','Submenú 1','Submenú 2',['Parámetros','parametros'])]}
};
