import {Component,OnInit} from '@angular/core'; import {CommonModule} from '@angular/common'; import {FormsModule} from '@angular/forms'; import {ActivatedRoute,Router} from '@angular/router';
import {Sidebar} from '../../../components/sidebar/sidebar'; import {Supbar} from '../../../components/supbar/supbar'; import {Tabla} from '../../../components/tabla/tabla'; import {DatosIdentificacion} from '../../../components/datosIdentificacion/datosIdentificacion'; import {DatosMovimiento} from '../../../components/datosMovimiento/datosMovimiento'; import {DocumentacionAdjunta} from '../../../components/documentacionAdjunta/documentacionAdjunta'; import {BarraAcciones} from '../../../directives/barraAcciones/barraAcciones';
import {ModuloAplicacion} from '../../../interfaces/modulo-aplicacion.interface'; import {ModuloAplicacionService} from '../../../services/modulo-aplicacion.service'; import {EmpresaService} from '../../../services/empresa.service'; import {Empresa} from '../../../interfaces/empresa.interface'; import {avisarAplicacion,confirmarAplicacion} from '../../../core/interaccion/dialogos.service';
@Component({selector:'ModulosAplicacion',standalone:true,imports:[CommonModule,FormsModule,Sidebar,Supbar,Tabla,DatosIdentificacion,DatosMovimiento,DocumentacionAdjunta,BarraAcciones],templateUrl:'./modulosAplicacion.html',styleUrl:'../../../styles/estiloGeneral.css'})
export class ModulosAplicacion implements OnInit{
 gestion=false; readonly empresaId=Number(localStorage.getItem('empresaId'))||0; empresaGestionId=0; empresas:Empresa[]=[]; vista:'tabla'|'formulario'|'adjuntos'='tabla'; modo:'insertar'|'ver'|'modificar'='insertar'; datos:ModuloAplicacion[]=[]; seleccionado:ModuloAplicacion|null=null; modulo=this.vacio();
 columnas=['id','codigo','titulo','descripcion','ruta','posicion','usuario','fecha','activo']; titulos={id:'Id Módulo',codigo:'Código',titulo:'Título',descripcion:'Descripción',ruta:'Ruta',posicion:'Posición',usuario:'Usuario Mod.',fecha:'Fecha Mod.',activo:'Activo'};
 constructor(private api:ModuloAplicacionService,private empresaApi:EmpresaService,route:ActivatedRoute,private router:Router){this.gestion=!!route.snapshot.data['gestion'];}
 ngOnInit(){if(this.gestion)this.empresaApi.obtenerEmpresas().subscribe({next:e=>this.empresas=e,error:()=>avisarAplicacion('No se pudieron consultar las empresas.')})} consultar(){this.vista='tabla';this.seleccionado=null;if(this.gestion&&!this.empresaGestionId){avisarAplicacion('Debe seleccionar una empresa.');return}const pet=this.gestion?this.api.gestion(this.empresaGestionId):this.api.listar();pet.subscribe({next:d=>this.datos=d,error:e=>avisarAplicacion(e?.error?.detail||'No se pudieron consultar los módulos.')});}
 insertar(){this.modulo=this.vacio();this.modo='insertar';this.vista='formulario'} ver(){if(!this.seleccionado)return;this.modulo={...this.seleccionado};this.modo='ver';this.vista='formulario'} modificar(){if(!this.seleccionado)return;this.modulo={...this.seleccionado};this.modo='modificar';this.vista='formulario'}
 guardar(){if(!this.valido())return;const pet=this.modo==='insertar'?this.api.guardar(this.modulo):this.api.actualizar(this.modulo);pet.subscribe({next:()=>{avisarAplicacion('Módulo guardado correctamente.');this.consultar()},error:e=>avisarAplicacion(e?.error?.message||'No se pudo guardar el módulo.')})}
 async eliminar(){if(!this.seleccionado||!await confirmarAplicacion('¿Desea eliminar el módulo seleccionado?',true))return;this.api.eliminar(this.seleccionado.id).subscribe({next:()=>this.consultar(),error:()=>avisarAplicacion('No se pudo eliminar el módulo.')})}
 adjuntos(){if(this.seleccionado){this.modulo={...this.seleccionado};this.vista='adjuntos'}} mover(i:number,d:number){const j=i+d;if(j<0||j>=this.datos.length)return;[this.datos[i],this.datos[j]]=[this.datos[j],this.datos[i]];this.datos=[...this.datos]}
 guardarGestion(){if(!this.empresaGestionId){avisarAplicacion('Debe seleccionar una empresa.');return}this.api.guardarGestion(this.empresaGestionId,this.datos).subscribe({next:guardados=>{this.datos=guardados;avisarAplicacion('Disponibilidad y orden guardados.')},error:e=>avisarAplicacion(e?.error?.detail||e?.error?.message||'No se pudo guardar la configuración.')})}
 cancelarGestion(){this.router.navigate(['/administracion'])}
 volver(){if(this.vista!=='tabla'){this.vista='tabla';return}this.router.navigate(['/administracion'])} valido(){if(!this.modulo.codigo.trim()||!this.modulo.titulo.trim()||!this.modulo.descripcion.trim()||!this.modulo.ruta.trim()){avisarAplicacion('Código, título, descripción y ruta son obligatorios.');return false}return true}
 vacio():ModuloAplicacion{return{id:0,codigo:'',titulo:'',descripcion:'',ruta:'',posicion:1,activo:true,usuario:localStorage.getItem('usuario')||'',fecha:''}}
}
