package com.jbrempresa.backend.dto.compras;
import java.math.BigDecimal;import java.time.*;import com.jbrempresa.backend.entity.Compra;import jakarta.validation.constraints.*;
import java.util.List;import jakarta.validation.Valid;import com.jbrempresa.backend.entity.CompraDetalle;
public final class CompraDtos{private CompraDtos(){}
 public record DetalleEntrada(@NotNull @Positive Long proId,@NotNull @Positive Integer comDetCan,@NotNull @PositiveOrZero BigDecimal comDetPre,@NotNull @DecimalMin("0") @DecimalMax("100") BigDecimal comDetDes,@NotNull @PositiveOrZero BigDecimal comDetIva){public CompraDetalle entidad(){CompraDetalle d=new CompraDetalle();d.setProId(proId);d.setComDetCan(comDetCan);d.setComDetPre(comDetPre);d.setComDetDes(comDetDes);d.setComDetIva(comDetIva);return d;}}

 public record Entrada(Long perIdCom,Long perIdVen,Long proId,@PositiveOrZero BigDecimal comImpSub,@PositiveOrZero BigDecimal comImpDes,@PositiveOrZero BigDecimal comImpIva,@PositiveOrZero BigDecimal comImpTot,@PositiveOrZero BigDecimal comImpPag,@PositiveOrZero BigDecimal comImpPen,LocalDate comFecPre,LocalDate comFecPed,LocalDate comFecAlb,LocalDate comFecFac,LocalDate comFecPag,@NotEmpty List<@Valid DetalleEntrada> detalles){public Compra entidad(){Compra v=new Compra();v.setPerIdCom(perIdCom);v.setPerIdVen(perIdVen);v.setProId(proId);v.setComImpSub(comImpSub);v.setComImpDes(comImpDes);v.setComImpIva(comImpIva);v.setComImpTot(comImpTot);v.setComImpPag(comImpPag);v.setComImpPen(comImpPen);v.setComFecPre(comFecPre);v.setComFecPed(comFecPed);v.setComFecAlb(comFecAlb);v.setComFecFac(comFecFac);v.setComFecPag(comFecPag);v.setDetalles(detalles.stream().map(DetalleEntrada::entidad).toList());return v;}}
 public record Salida(Long comId,Long empId,Long perIdCom,Long perIdVen,Long proId,BigDecimal comImpSub,BigDecimal comImpDes,BigDecimal comImpIva,BigDecimal comImpTot,BigDecimal comImpPag,BigDecimal comImpPen,LocalDate comFecPre,LocalDate comFecPed,LocalDate comFecAlb,LocalDate comFecFac,LocalDate comFecPag,Boolean comAct,String comUsuMov,LocalDateTime comFecMov,List<CompraDetalle> detalles,Long proveedorEmpresaId,Long pedidoVentaId,String pedidoVentaNumero,String proveedorNombre){public static Salida desde(Compra v){return new Salida(v.getComId(),v.getEmpId(),v.getPerIdCom(),v.getPerIdVen(),v.getProId(),v.getComImpSub(),v.getComImpDes(),v.getComImpIva(),v.getComImpTot(),v.getComImpPag(),v.getComImpPen(),v.getComFecPre(),v.getComFecPed(),v.getComFecAlb(),v.getComFecFac(),v.getComFecPag(),v.getComAct(),v.getComUsuMov(),v.getComFecMov(),v.getDetalles(),v.getProveedorEmpresaId(),v.getPedidoVentaId(),v.getPedidoVentaNumero(),v.getProveedorNombre());}}
}
