import {BarraAcciones} from '../../../directives/barraAcciones/barraAcciones';
import {avisarAplicacion,confirmarAplicacion} from '../../../core/interaccion/dialogos.service';
import { Component,OnInit } from '@angular/core'; import { CommonModule } from '@angular/common'; import { FormsModule } from '@angular/forms'; import { ActivatedRoute,Router } from '@angular/router';
import { Sidebar } from '../../../components/sidebar/sidebar'; import { Supbar } from '../../../components/supbar/supbar'; import { Tabla } from '../../../components/tabla/tabla'; import { DocumentacionAdjunta } from '../../../components/documentacionAdjunta/documentacionAdjunta'; import { SelectorBusqueda } from '../../../components/selectorBusqueda/selectorBusqueda';
import { ComunicacionService } from '../../../services/comunicacion.service'; import { Comunicacion,Mensaje,PropuestaRespuesta } from '../../../interfaces/comunicacion.interface';
import { PersonaService } from '../../../services/persona.service'; import { UsuarioService } from '../../../services/usuario.service'; import { AreaOrganizativaService } from '../../../services/area-organizativa.service'; import { Persona } from '../../../interfaces/persona.interface';
@Component({selector:'bandeja-comunicaciones',standalone:true,imports:[CommonModule,FormsModule,Sidebar,Supbar,Tabla,DocumentacionAdjunta,SelectorBusqueda,BarraAcciones],templateUrl:'./bandejaComunicaciones.html',styleUrl:'./bandejaComunicaciones.css'})
export class BandejaComunicaciones implements OnInit {
 titulo='BANDEJA DE ENTRADA';descripcion='Consulta mensajes recibidos todavía pendientes de vincular a una conversación.';filtro='bandeja';vista:'tabla'|'nueva'|'mensajeEntrada'|'detalle'='tabla';
 datos:any[]=[];conversaciones:Comunicacion[]=[];seleccionada:Comunicacion|null=null;mensajeEntrada:Mensaje|null=null;mensajes:Mensaje[]=[];
 columnas:string[]=[];titulosColumnas:any={};
 nueva:any={menCan:'SIMULADO',menRem:'',menAsu:'',menCon:'',menNomRem:'',menDniRem:'',menTelRem:'',menEmaRem:''};
 clasificacion:any={comTip:'CONVERSACION',comAsu:'',comCan:'SIMULADO'};conversacionDestino=0;
 intencionSeleccionada='OTRO';
 readonly intenciones=[{id:'CONSULTA_PRODUCTO',texto:'Consulta de producto'},{id:'SOLICITUD_PRESUPUESTO',texto:'Solicitud de presupuesto'},{id:'PEDIDO',texto:'Pedido'},{id:'CITA_RESERVA',texto:'Cita o reserva'},{id:'INCIDENCIA',texto:'Incidencia o reclamación'},{id:'INFORMACION_GENERAL',texto:'Información general'},{id:'OTRO',texto:'Otra intención'}];
 candidatos:Persona[]=[];personas:Persona[]=[];personaSeleccionada=0;mostrarAltaPersona=false;altaPersona:any={};usuarios:any[]=[];areas:any[]=[];usuarioAsignado:number|null=null;areaAsignada:number|null=null;
 respuesta='';autorRespuesta:'USUARIO'|'CLIENTE'|'IA'|'SISTEMA'='USUARIO';direccionRespuesta:'ENTRADA'|'SALIDA'|'INTERNA'='SALIDA';
 propuestas:PropuestaRespuesta[]=[];propuestaActiva:PropuestaRespuesta|null=null;contenidoPropuesta='';generandoPropuesta=false;
 constructor(private service:ComunicacionService,private personaService:PersonaService,private usuarioService:UsuarioService,private areaService:AreaOrganizativaService,private route:ActivatedRoute,private router:Router){}
 ngOnInit(){this.usuarioService.obtenerUsuarios().subscribe(v=>this.usuarios=v);this.areaService.consultar().subscribe(v=>this.areas=v.filter(x=>x.areAct));this.personaService.obtenerPersonasSelector().subscribe({next:v=>{this.personas=v;this.datos=this.enriquecerPersonas(this.datos);},error:e=>this.error(e)});this.route.data.subscribe(d=>{this.filtro=d['filtro']||'bandeja';this.configurar();this.configurarColumnasClasificacion();this.consultar();});}

 configurarColumnasClasificacion(){if(this.filtro==='bandeja'){this.columnas=['menId','menFecRec','menAsu','menNomRem','menInt','menEstCla','menEst'];this.titulosColumnas={menId:'Id',menFecRec:'Recibido',menAsu:'Asunto',menNomRem:'Nombre',menInt:'Intención',menEstCla:'Clasificación',menEst:'Estado'};}else{this.columnas=['comId','comTip','comInt','comCan','comEst','comAsu','personaNomCom','usuId','areId','comFecUlt'];this.titulosColumnas={comId:'Id',comTip:'Tipo',comInt:'Intención',comCan:'Canal',comEst:'Estado',comAsu:'Asunto',personaNomCom:'Persona',usuId:'Usuario',areId:'Área',comFecUlt:'Último mensaje'};}}
 configurar(){if(this.filtro==='bandeja'){this.titulo='BANDEJA DE ENTRADA';this.descripcion='Consulta mensajes recibidos todavía pendientes de identificar y vincular a una conversación nueva o existente.';this.columnas=['menId','menFecRec','menAsu','menNomRem','menDniRem','menTelRem','menEmaRem','menEst'];this.titulosColumnas={menId:'Id',menFecRec:'Recibido',menAsu:'Asunto',menNomRem:'Nombre',menDniRem:'DNI',menTelRem:'Teléfono',menEmaRem:'Correo',menEst:'Estado'};}else{this.titulo=this.filtro==='pendientes'?'PENDIENTES DE REVISIÓN':'CONVERSACIONES';this.descripcion=this.filtro==='pendientes'?'Consulta conversaciones que necesitan intervención humana o presentan un error.':'Consulta los hilos completos formados por todos los mensajes vinculados a cada conversación.';this.columnas=['comId','comTip','comCan','comEst','comAsu','personaNomCom','usuId','areId','comFecUlt'];this.titulosColumnas={comId:'Id',comTip:'Tipo',comCan:'Canal',comEst:'Estado',comAsu:'Asunto',personaNomCom:'Persona',usuId:'Usuario',areId:'Área',comFecUlt:'Último mensaje'};}}
 consultar(){this.vista='tabla';this.seleccionada=null;this.mensajeEntrada=null;if(this.filtro==='bandeja')this.service.entrada().subscribe({next:v=>this.datos=v,error:e=>this.error(e)});else this.service.consultar().subscribe({next:v=>{this.conversaciones=v;const filas=this.filtro==='pendientes'?v.filter(x=>x.comEst==='PENDIENTE_USUARIO'||x.comEst==='ERROR'):v;this.datos=this.enriquecerPersonas(filas);},error:e=>this.error(e)});}
 private enriquecerPersonas(filas:any[]){return filas.map(fila=>({...fila,personaNomCom:this.personas.find(persona=>Number(persona.perId)===Number(fila.perId))?.perNomCom||''}));}
 seleccionar(fila:any){if(this.filtro==='bandeja'){this.mensajeEntrada=fila;this.intencionSeleccionada=fila.menInt||'OTRO';this.seleccionada=null;}else{this.seleccionada=fila;this.mensajeEntrada=null;}}
 abrirSeleccionada(){if(this.mensajeEntrada){this.clasificacion={comTip:'CONVERSACION',comAsu:this.mensajeEntrada.menAsu||'',comCan:this.mensajeEntrada.menCan||'SIMULADO'};this.personaSeleccionada=this.mensajeEntrada.perId||0;this.mostrarAltaPersona=false;this.prepararAltaPersona();this.service.candidatos(this.mensajeEntrada.menId).subscribe(v=>this.candidatos=v);if(this.mensajeEntrada.perId)this.cargarConversacionesPersona(this.mensajeEntrada.perId);else this.conversaciones=[];this.vista='mensajeEntrada';return;}if(!this.seleccionada)return;this.usuarioAsignado=this.seleccionada.usuId;this.areaAsignada=this.seleccionada.areId;this.cargarDetalle();}
 private cargarDetalle(){if(!this.seleccionada)return;this.service.mensajes(this.seleccionada.comId).subscribe({next:v=>{this.mensajes=v;this.vista='detalle';},error:e=>this.error(e)});this.service.propuestas(this.seleccionada.comId).subscribe({next:v=>{this.propuestas=v;this.propuestaActiva=v.find(p=>p.prrEst==='PENDIENTE')||null;this.contenidoPropuesta=this.propuestaActiva?.prrCon||'';},error:e=>this.error(e)});}
 generarPropuesta(){if(!this.seleccionada||this.generandoPropuesta)return;this.generandoPropuesta=true;this.service.generarPropuesta(this.seleccionada.comId).subscribe({next:p=>{this.propuestaActiva=p;this.contenidoPropuesta=p.prrCon;this.generandoPropuesta=false;},error:e=>{this.generandoPropuesta=false;this.error(e)}});}
 aprobarPropuesta(){if(!this.seleccionada||!this.propuestaActiva||!this.contenidoPropuesta.trim())return;this.service.aprobarPropuesta(this.seleccionada.comId,this.propuestaActiva.prrId,this.contenidoPropuesta).subscribe({next:()=>this.cargarDetalle(),error:e=>this.error(e)});}
 rechazarPropuesta(){if(!this.seleccionada||!this.propuestaActiva)return;this.service.rechazarPropuesta(this.seleccionada.comId,this.propuestaActiva.prrId).subscribe({next:()=>this.cargarDetalle(),error:e=>this.error(e)});}
 nuevaEntrada(){this.nueva={menCan:'SIMULADO',menRem:'',menAsu:'',menCon:'',menNomRem:'',menDniRem:'',menTelRem:'',menEmaRem:''};this.vista='nueva';}
 guardarEntrada(){if(!this.nueva.menCon.trim()){avisarAplicacion('El contenido del mensaje es obligatorio.');return;}this.service.recibir(this.nueva).subscribe({next:()=>this.consultar(),error:e=>this.error(e)});}
 confirmarPersona(){if(!this.mensajeEntrada||!this.personaSeleccionada)return;this.service.confirmarPersona(this.mensajeEntrada.menId,this.personaSeleccionada).subscribe({next:m=>{this.mensajeEntrada=m;this.cargarConversacionesPersona(this.personaSeleccionada);},error:e=>this.error(e)});}
 confirmarClasificacion(){if(!this.mensajeEntrada||!this.intencionSeleccionada)return;this.service.confirmarClasificacion(this.mensajeEntrada.menId,this.intencionSeleccionada).subscribe({next:m=>this.mensajeEntrada=m,error:e=>this.error(e)});}
 nombrePersonaConfirmada(){const id=this.mensajeEntrada?.perId;const persona=this.personas.find(p=>p.perId===id);return persona?`${persona.perNomCom} (${persona.perDoc})`:`Persona ${id}`;}
 private cargarConversacionesPersona(id:number){this.service.conversacionesPersona(id).subscribe(v=>this.conversaciones=v);}
 private prepararAltaPersona(){this.altaPersona={perTipDoc:'DNI',perDoc:this.mensajeEntrada?.menDniRem||'',perNom:this.mensajeEntrada?.menNomRem||'',perApe1:'',perApe2:'',perTel:this.mensajeEntrada?.menTelRem||'',perEma:this.mensajeEntrada?.menEmaRem||'',perNomCom:this.mensajeEntrada?.menNomRem||'',perFecNac:'',domId:0,perCoX:0,perCoY:0,perHus:0};}
 crearPersona(){if(!this.mensajeEntrada||!this.altaPersona.perTipDoc||!this.altaPersona.perDoc?.trim()||!this.altaPersona.perNom?.trim()||!this.altaPersona.perApe1?.trim()){avisarAplicacion('Tipo de documento, documento, nombre y primer apellido son obligatorios.');return;}this.altaPersona.perNomCom=[this.altaPersona.perNom,this.altaPersona.perApe1,this.altaPersona.perApe2].filter(Boolean).join(' ');this.personaService.guardar(this.altaPersona as Persona).subscribe({next:(p:any)=>{this.personaSeleccionada=p.perId;this.mostrarAltaPersona=false;this.confirmarPersona();},error:e=>this.error(e)});}
 crearConversacion(){if(!this.mensajeEntrada||!this.clasificacion.comAsu.trim()){avisarAplicacion('El asunto de la conversación es obligatorio.');return;}this.service.crearDesdeMensaje(this.mensajeEntrada.menId,this.clasificacion).subscribe({next:()=>this.consultar(),error:e=>this.error(e)});}
 vincularConversacion(){if(!this.mensajeEntrada||!this.conversacionDestino)return;this.service.vincular(this.mensajeEntrada.menId,this.conversacionDestino).subscribe({next:()=>this.consultar(),error:e=>this.error(e)});}
 responder(){if(!this.seleccionada||!this.respuesta.trim())return;this.service.agregarMensaje(this.seleccionada.comId,{menDir:this.direccionRespuesta,menAut:this.autorRespuesta,menCon:this.respuesta}).subscribe({next:()=>{this.respuesta='';this.abrirSeleccionada();},error:e=>this.error(e)});}
 cambiarEstado(estado:string){if(!this.seleccionada)return;this.service.cambiarEstado(this.seleccionada.comId,estado).subscribe({next:()=>this.consultar(),error:e=>this.error(e)});}
 guardarAsignacion(){if(!this.seleccionada)return;this.service.asignar(this.seleccionada.comId,this.usuarioAsignado,this.areaAsignada).subscribe({next:v=>this.seleccionada=v,error:e=>this.error(e)});}
 volver(){if(this.vista!=='tabla'){this.consultar();return;}this.router.navigate(['/comunicaciones']);}
 private error(e:any){console.error(e);const mensaje=e?.error?.message||e?.error?.mensaje||(e?.status===404?'El servicio de Comunicaciones no está disponible. Reinicie el backend.':e?.status===0?'La solicitud no llegó al backend. Compruebe que está iniciado y que CORS permite la operación.':`No se pudo completar la operación${e?.status?' (HTTP '+e.status+')':''}.`);avisarAplicacion(mensaje);}
}
