package com.jbrempresa.backend.service;
import static com.jbrempresa.backend.dto.agenda.AgendaDtos.*;
import java.time.*;import java.time.temporal.ChronoUnit;import java.util.*;
import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
import com.jbrempresa.backend.core.context.ContextoOperacion;import com.jbrempresa.backend.entity.*;import com.jbrempresa.backend.exception.*;import com.jbrempresa.backend.repository.*;
@Service public class AgendaService{
 private final RecursoAgendableRepository recursos;private final HorarioRecursoRepository horarios;private final ExcepcionRecursoRepository excepciones;private final ReservaRepository reservas;private final ReservaRecursoRepository reservaRecursos;private final TareaReservaRepository tareas;private final ReprogramacionReservaRepository reprogramaciones;private final PersonaRepository personas;private final RecursoOperativoRepository recursosOperativos;private final DomicilioRepository domicilios;private final DocumentoVentaRepository documentos;private final ComunicacionRepository comunicaciones;private final ContextoOperacion ctx;
 public AgendaService(RecursoAgendableRepository a,HorarioRecursoRepository h,ExcepcionRecursoRepository e,ReservaRepository r,ReservaRecursoRepository rr,TareaReservaRepository t,ReprogramacionReservaRepository rp,PersonaRepository p,RecursoOperativoRepository ro,DomicilioRepository d,DocumentoVentaRepository dv,ComunicacionRepository co,ContextoOperacion x){recursos=a;horarios=h;excepciones=e;reservas=r;reservaRecursos=rr;tareas=t;reprogramaciones=rp;personas=p;recursosOperativos=ro;domicilios=d;documentos=dv;comunicaciones=co;ctx=x;}
 public List<RecursoSalida> recursos(){return recursos.findByEmpIdAndRagActTrueOrderByRagTipAscRagNomAsc(ctx.empresaId()).stream().filter(recurso->referenciaVigente(recurso)).map(recurso->salida(recurso)).toList();}
 @Transactional public RecursoSalida guardarRecurso(RecursoEntrada in){RecursoAgendable r=recursos.findByEmpIdAndRagTipAndRagRefIdAndRagActTrue(ctx.empresaId(),in.ragTip(),in.ragRefId()).orElseGet(RecursoAgendable::new);if("EMPLEADO".equals(in.ragTip())){var empleado=recursosOperativos.findByEmpIdAndReoIdAndReoActTrue(ctx.empresaId(),in.ragRefId()).filter(x->"EMPLEADO".equals(x.getReoTip())&&!"B".equals(x.getReoTipMov())).orElseThrow(()->negocio("Empleado no válido."));r.setRagNom(empleado.getReoNom());r.setRagCap(1);}else{var d=domicilios.findByEmpIdAndDomIdAndDomActTrue(ctx.empresaId(),in.ragRefId()).filter(x->!"B".equals(x.getDomTipMov())).orElseThrow(()->negocio("Domicilio no válido."));r.setRagNom(d.getDomDir());r.setRagCap(in.ragCap());}r.setEmpId(ctx.empresaId());r.setRagTip(in.ragTip());r.setRagRefId(in.ragRefId());r.setRagMarPre(in.ragMarPre());r.setRagMarPos(in.ragMarPos());r.setRagHorVis(in.ragHorVis());auditar(r);return salida(recursos.save(r));}
 public List<HorarioSalida> horarios(Long rag){recurso(rag);return horarios.findByEmpIdAndRagIdAndHorActTrueOrderByHorDiaAscHorIniAsc(ctx.empresaId(),rag).stream().map(h->new HorarioSalida(h.getHorId(),h.getHorDia(),h.getHorIni(),h.getHorFin())).toList();}
 @Transactional public List<HorarioSalida> reemplazarHorarios(Long rag,List<HorarioEntrada> entrada){recurso(rag);validarFranjas(entrada);horarios.deleteByEmpIdAndRagId(ctx.empresaId(),rag);horarios.flush();entrada.forEach(in->{HorarioRecurso h=new HorarioRecurso();h.setEmpId(ctx.empresaId());h.setRagId(rag);h.setHorDia(in.horDia());h.setHorIni(in.horIni());h.setHorFin(in.horFin());h.setHorUsuMov(ctx.nombreUsuario());h.setHorFecMov(ctx.fechaActual());h.setHorAct(true);horarios.save(h);});return horarios(rag);}
 public List<ExcepcionSalida> excepciones(Long rag,LocalDate desde,LocalDate hasta){recurso(rag);return excepciones.findByEmpIdAndRagIdAndExrFecBetweenAndExrActTrueOrderByExrFecAscExrIniAsc(ctx.empresaId(),rag,desde,hasta).stream().map(excepcion->salida(excepcion)).toList();}
 @Transactional public ExcepcionSalida guardarExcepcion(Long rag,ExcepcionEntrada in){recurso(rag);if((in.exrIni()==null)!=(in.exrFin()==null)||in.exrIni()!=null&&!in.exrIni().isBefore(in.exrFin()))throw negocio("La franja de la excepción no es válida.");ExcepcionRecurso e=new ExcepcionRecurso();e.setEmpId(ctx.empresaId());e.setRagId(rag);e.setExrFec(in.exrFec());e.setExrIni(in.exrIni());e.setExrFin(in.exrFin());e.setExrDis(in.exrDis());e.setExrCap(in.exrCap());e.setExrMot(in.exrMot());e.setExrUsuMov(ctx.nombreUsuario());e.setExrFecMov(ctx.fechaActual());e.setExrAct(true);return salida(excepciones.save(e));}
 @Transactional public void eliminarExcepcion(Long id){ExcepcionRecurso e=excepciones.findByEmpIdAndExrIdAndExrActTrue(ctx.empresaId(),id).orElseThrow(()->noEncontrado("Excepción no encontrada."));e.setExrAct(false);e.setExrUsuMov(ctx.nombreUsuario());e.setExrFecMov(ctx.fechaActual());excepciones.save(e);}
 public List<ReservaSalida> reservas(LocalDateTime desde,LocalDateTime hasta){if(!desde.isBefore(hasta))throw negocio("El periodo de consulta no es válido.");return reservas.findByEmpIdAndResIniLessThanAndResFinGreaterThanAndResActTrueOrderByResIniAsc(ctx.empresaId(),hasta,desde).stream().map(reserva->salida(reserva)).toList();}
 @Transactional public ReservaSalida crearReserva(ReservaEntrada in){validarReferencias(in);validarPeriodo(in.resIni(),in.resFin());RecursoAgendable asignado=bloquearRecurso(in.ragId());validarDisponibilidad(asignado,in.resIni(),in.resFin(),null);Reserva r=new Reserva();r.setEmpId(ctx.empresaId());r.setPerId(in.perId());r.setDovId(in.dovId());r.setComId(in.comId());r.setResIni(in.resIni());r.setResFin(in.resFin());r.setResEst("PENDIENTE");r.setResDurMin((int)ChronoUnit.MINUTES.between(in.resIni(),in.resFin()));r.setResTit(in.resTit());r.setResObs(in.resObs());auditar(r);r=reservas.save(r);guardarAsignacion(r,asignado);guardarTareas(r,in.tareas());return salida(r);}
 @Transactional public ReservaSalida reprogramar(Long id,ReprogramacionEntrada in){Reserva r=reserva(id);validarPeriodo(in.resIni(),in.resFin());if(List.of("TERMINADA","CANCELADA","AUSENCIA").contains(r.getResEst()))throw negocio("El estado de la reserva no permite reprogramarla.");ReservaRecurso actual=reservaRecursos.findByEmpIdAndResIdAndRerActTrue(ctx.empresaId(),id).stream().findFirst().orElseThrow(()->negocio("La reserva no tiene agenda."));RecursoAgendable asignado=bloquearRecurso(actual.getRagId());validarDisponibilidad(asignado,in.resIni(),in.resFin(),id);ReprogramacionReserva rp=new ReprogramacionReserva();rp.setEmpId(ctx.empresaId());rp.setResId(id);rp.setRprIniAnt(r.getResIni());rp.setRprFinAnt(r.getResFin());rp.setRprIniNue(in.resIni());rp.setRprFinNue(in.resFin());rp.setRprMot(in.motivo());rp.setRprUsuMov(ctx.nombreUsuario());rp.setRprFecMov(ctx.fechaActual());rp.setRprAct(true);reprogramaciones.save(rp);r.setResIni(in.resIni());r.setResFin(in.resFin());r.setResDurMin((int)ChronoUnit.MINUTES.between(in.resIni(),in.resFin()));auditar(r);reservas.save(r);reservaRecursos.deleteByEmpIdAndResId(ctx.empresaId(),id);guardarAsignacion(r,asignado);return salida(r);}
 @Transactional public ReservaSalida cambiarEstado(Long id,String estado){Reserva r=reserva(id);validarTransicion(r.getResEst(),estado);r.setResEst(estado);auditar(r);return salida(reservas.save(r));}
 public List<ReprogramacionSalida> historial(Long id){reserva(id);return reprogramaciones.findByEmpIdAndResIdAndRprActTrueOrderByRprFecMovDesc(ctx.empresaId(),id).stream().map(x->new ReprogramacionSalida(x.getRprId(),x.getRprIniAnt(),x.getRprFinAnt(),x.getRprIniNue(),x.getRprFinNue(),x.getRprMot(),x.getRprUsuMov(),x.getRprFecMov())).toList();}
 private void validarReferencias(ReservaEntrada in){if(in.perId()!=null)personas.findByEmpIdAndPerIdAndPerActTrue(ctx.empresaId(),in.perId()).filter(x->!"B".equals(x.getPerTipMov())).orElseThrow(()->negocio("Persona no válida."));if(in.dovId()!=null)documentos.findByEmpIdAndDovId(ctx.empresaId(),in.dovId()).orElseThrow(()->negocio("Documento comercial no válido."));if(in.comId()!=null)comunicaciones.findByEmpIdAndComIdAndComActTrue(ctx.empresaId(),in.comId()).orElseThrow(()->negocio("Conversación no válida."));}
 private void validarPeriodo(LocalDateTime ini,LocalDateTime fin){if(!ini.isBefore(fin)||!ini.toLocalDate().equals(fin.toLocalDate()))throw negocio("La reserva debe comenzar y terminar en el mismo día.");}
 private RecursoAgendable bloquearRecurso(Long id){return recursos.findForUpdateByEmpIdAndRagIdAndRagActTrue(ctx.empresaId(),id).orElseThrow(()->negocio("Agenda no válida."));}
 private void validarDisponibilidad(RecursoAgendable r,LocalDateTime ini,LocalDateTime fin,Long excluir){if(!referenciaVigente(r))throw negocio("El empleado no está activo y operativo.");LocalDateTime ocuIni=ini.minusMinutes(r.getRagMarPre());LocalDateTime ocuFin=fin.plusMinutes(r.getRagMarPos());if(!dentroHorario(r,ocuIni,ocuFin))throw negocio("La agenda "+r.getRagNom()+" está fuera de horario o no disponible.");int capacidad=capacidad(r,ocuIni,ocuFin);if(reservaRecursos.contarSolapamientos(ctx.empresaId(),r.getRagId(),ocuIni,ocuFin,excluir)>=capacidad)throw negocio("La agenda "+r.getRagNom()+" no tiene capacidad disponible.");}
 private boolean referenciaVigente(RecursoAgendable r){if(!"EMPLEADO".equals(r.getRagTip()))return true;return recursosOperativos.findByEmpIdAndReoIdAndReoActTrue(ctx.empresaId(),r.getRagRefId()).filter(x->!"B".equals(x.getReoTipMov())&&Boolean.TRUE.equals(x.getReoOpe())).isPresent();}
 private boolean dentroHorario(RecursoAgendable r,LocalDateTime ini,LocalDateTime fin){List<ExcepcionRecurso> ex=excepciones.findByEmpIdAndRagIdAndExrFecBetweenAndExrActTrueOrderByExrFecAscExrIniAsc(ctx.empresaId(),r.getRagId(),ini.toLocalDate(),fin.toLocalDate());boolean cerrado=ex.stream().anyMatch(e->!e.getExrDis()&&solapa(e,ini.toLocalTime(),fin.toLocalTime()));if(cerrado)return false;boolean apertura=ex.stream().anyMatch(e->e.getExrDis()&&cubre(e,ini.toLocalTime(),fin.toLocalTime()));if(apertura)return true;int dia=ini.getDayOfWeek().getValue();return horarios.findByEmpIdAndRagIdAndHorActTrueOrderByHorDiaAscHorIniAsc(ctx.empresaId(),r.getRagId()).stream().anyMatch(h->h.getHorDia()==dia&&!ini.toLocalTime().isBefore(h.getHorIni())&&!fin.toLocalTime().isAfter(h.getHorFin()));}
 private int capacidad(RecursoAgendable r,LocalDateTime ini,LocalDateTime fin){return excepciones.findByEmpIdAndRagIdAndExrFecBetweenAndExrActTrueOrderByExrFecAscExrIniAsc(ctx.empresaId(),r.getRagId(),ini.toLocalDate(),fin.toLocalDate()).stream().filter(e->e!=null).filter(e->e.getExrCap()!=null&&solapa(e,ini.toLocalTime(),fin.toLocalTime())).map(e->e.getExrCap()).findFirst().orElse(r.getRagCap());}
 private boolean solapa(ExcepcionRecurso e,LocalTime ini,LocalTime fin){return e.getExrIni()==null||e.getExrIni().isBefore(fin)&&e.getExrFin().isAfter(ini);}private boolean cubre(ExcepcionRecurso e,LocalTime ini,LocalTime fin){return e.getExrIni()==null||!ini.isBefore(e.getExrIni())&&!fin.isAfter(e.getExrFin());}
 private void guardarAsignacion(Reserva r,RecursoAgendable a){ReservaRecurso x=new ReservaRecurso();x.setEmpId(ctx.empresaId());x.setResId(r.getResId());x.setRagId(a.getRagId());x.setRerIniOcu(r.getResIni().minusMinutes(a.getRagMarPre()));x.setRerFinOcu(r.getResFin().plusMinutes(a.getRagMarPos()));x.setRerUsuMov(ctx.nombreUsuario());x.setRerFecMov(ctx.fechaActual());x.setRerAct(true);reservaRecursos.save(x);}
 private void guardarTareas(Reserva r,List<TareaEntrada> lista){List<TareaEntrada> tareasValidas=lista.stream().filter(tarea->tarea!=null).toList();if(tareasValidas.stream().map(tarea->tarea.tarOrd()).distinct().count()!=tareasValidas.size())throw negocio("El orden de las tareas no se puede repetir.");tareasValidas.forEach(in->{if(in.ragId()!=null)recurso(in.ragId());TareaReserva t=new TareaReserva();t.setEmpId(ctx.empresaId());t.setResId(r.getResId());t.setRagId(in.ragId());t.setTarOrd(in.tarOrd());t.setTarTit(in.tarTit());t.setTarDurMin(in.tarDurMin());t.setTarEst("PENDIENTE");t.setTarUsuMov(ctx.nombreUsuario());t.setTarFecMov(ctx.fechaActual());t.setTarAct(true);tareas.save(t);});}
 private void validarFranjas(List<HorarioEntrada> lista){for(HorarioEntrada a:lista){if(!a.horIni().isBefore(a.horFin()))throw negocio("Existe una franja horaria no válida.");for(HorarioEntrada b:lista)if(a!=b&&a.horDia().equals(b.horDia())&&a.horIni().isBefore(b.horFin())&&a.horFin().isAfter(b.horIni()))throw negocio("Las franjas horarias no pueden solaparse.");}}
 private void validarTransicion(String desde,String hasta){Map<String,Set<String>> m=Map.of("PENDIENTE",Set.of("CONFIRMADA","CANCELADA"),"CONFIRMADA",Set.of("EN_CURSO","CANCELADA","AUSENCIA"),"EN_CURSO",Set.of("TERMINADA","CANCELADA"),"TERMINADA",Set.of(),"CANCELADA",Set.of(),"AUSENCIA",Set.of());if(desde.equals(hasta)||!m.getOrDefault(desde,Set.of()).contains(hasta))throw negocio("Transición de estado no permitida.");}
 private ReservaSalida salida(Reserva r){Long ragId=reservaRecursos.findByEmpIdAndResIdAndRerActTrue(ctx.empresaId(),r.getResId()).stream().filter(asignacion->asignacion!=null).findFirst().map(asignacion->asignacion.getRagId()).orElse(null);List<TareaSalida> ts=tareas.findByEmpIdAndResIdAndTarActTrueOrderByTarOrdAsc(ctx.empresaId(),r.getResId()).stream().filter(tarea->tarea!=null).map(t->new TareaSalida(t.getTarId(),t.getRagId(),t.getTarOrd(),t.getTarTit(),t.getTarDurMin(),t.getTarEst())).toList();return new ReservaSalida(r.getResId(),r.getPerId(),r.getDovId(),r.getComId(),r.getResIni(),r.getResFin(),r.getResEst(),r.getResDurMin(),r.getResTit(),r.getResObs(),ragId,ts);}
 private RecursoSalida salida(RecursoAgendable r){return new RecursoSalida(r.getRagId(),r.getRagTip(),r.getRagRefId(),r.getRagNom(),r.getRagCap(),r.getRagMarPre(),r.getRagMarPos(),r.getRagHorVis());}private ExcepcionSalida salida(ExcepcionRecurso e){return new ExcepcionSalida(e.getExrId(),e.getExrFec(),e.getExrIni(),e.getExrFin(),e.getExrDis(),e.getExrCap(),e.getExrMot());}
 private RecursoAgendable recurso(Long id){return recursos.findByEmpIdAndRagIdAndRagActTrue(ctx.empresaId(),id).orElseThrow(()->noEncontrado("Recurso no encontrado."));}private Reserva reserva(Long id){return reservas.findByEmpIdAndResIdAndResActTrue(ctx.empresaId(),id).orElseThrow(()->noEncontrado("Reserva no encontrada."));}private void auditar(RecursoAgendable r){r.setRagUsuMov(ctx.nombreUsuario());r.setRagFecMov(ctx.fechaActual());r.setRagAct(true);}private void auditar(Reserva r){r.setResUsuMov(ctx.nombreUsuario());r.setResFecMov(ctx.fechaActual());r.setResAct(true);}private ReglaNegocioException negocio(String m){return new ReglaNegocioException("AGENDA",m);}private RecursoNoEncontradoException noEncontrado(String m){return new RecursoNoEncontradoException(m);}
}
