package com.jbrempresa.backend.service;
import java.time.LocalDateTime;import java.util.*;import org.springframework.beans.BeanUtils;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import com.jbrempresa.backend.entity.Componente;import com.jbrempresa.backend.repository.ComponenteRepository;
@Service public class ComponenteService{private final ComponenteRepository repo;public ComponenteService(ComponenteRepository r){repo=r;}
 public List<Componente> listar(Long emp){return emp==null?repo.findByCmpActTrueOrderByEmpIdAscCmpIdAsc():repo.findByEmpIdAndCmpActTrueOrderByCmpId(emp);}public List<Componente> historico(Long emp,Long id){vigente(emp,id);return repo.findByEmpIdAndCmpIdOrderByCmpIdHisDesc(emp,id);}
 @Transactional public Componente guardar(Long emp,String usu,Componente i){i.setEmpId(emp);i.setCmpId(repo.siguiente(emp));i.setCmpIdHis(1L);mov(i,"A","Alta del registro",usu);return repo.save(i);}
 @Transactional public Componente actualizar(Long emp,String usu,Long id,Componente i){Componente a=vigente(emp,id);a.setCmpAct(false);repo.saveAndFlush(a);i.setEmpId(emp);i.setCmpId(id);i.setCmpIdHis(a.getCmpIdHis()+1);mov(i,"M","Modificación del registro",usu);return repo.save(i);}
 @Transactional public void eliminar(Long emp,Long id){vigente(emp,id);repo.deleteAll(repo.findByEmpIdAndCmpIdOrderByCmpIdHisDesc(emp,id));}
 @Transactional public Componente baja(Long emp,String usu,Long id){Componente a=vigente(emp,id);a.setCmpAct(false);repo.saveAndFlush(a);Componente b=new Componente();BeanUtils.copyProperties(a,b);b.setCmpIdHis(a.getCmpIdHis()+1);mov(b,"B","Baja del registro",usu);return repo.save(b);}
 @Transactional public Componente deshacer(Long emp,Long id){Componente actual=vigente(emp,id);if(actual.getCmpIdHis()<=1)throw new IllegalStateException("No existen movimientos anteriores.");Componente anterior=repo.findByEmpIdAndCmpIdAndCmpIdHis(emp,id,actual.getCmpIdHis()-1).orElseThrow();repo.delete(actual);repo.flush();anterior.setCmpAct(true);return repo.save(anterior);}
 private void mov(Componente i,String tipo,String causa,String usu){i.setCmpTipMov(tipo);i.setCmpCauMov(causa);i.setCmpUsuMov(usu);i.setCmpFecMov(LocalDateTime.now());i.setCmpAct(true);}private Componente vigente(Long emp,Long id){return repo.findByEmpIdAndCmpIdAndCmpActTrue(emp,id).orElseThrow(()->new RuntimeException("Componente no encontrado."));}
}
