package com.jbrempresa.backend.service;
import com.jbrempresa.backend.core.context.ContextoOperacion;import com.jbrempresa.backend.dto.administracion.EmpresaRelacionDtos.*;import com.jbrempresa.backend.entity.*;import com.jbrempresa.backend.repository.*;import jakarta.transaction.Transactional;import org.springframework.stereotype.Service;import java.time.*;import java.util.*;
@Service public class EmpresaRelacionService{private final EmpresaRelacionMovimientoRepository movimientos;private final EmpresaRelacionRepository repo;private final EmpresaRepository empresas;private final ContextoOperacion contexto;public EmpresaRelacionService(EmpresaRelacionRepository r,EmpresaRepository e,ContextoOperacion c,EmpresaRelacionMovimientoRepository m){movimientos=m;repo=r;empresas=e;contexto=c;}public List<Salida> listar(){return repo.findByEmpIdOrderById(contexto.empresaId()).stream().map(this::salida).toList();}public List<Opcion> empresas(){return empresas.findAll().stream().filter(e->!e.getEmpId().equals(contexto.empresaId())).map(e->new Opcion(e.getEmpId(),e.getEmpNom())).toList();}public List<Opcion> proveedores(){return repo.findByEmpIdAndTipoAndActivaTrueOrderById(contexto.empresaId(),"PROVEEDOR").stream().map(r->empresas.findById(r.getEmpresaRelacionadaId()).map(e->new Opcion(e.getEmpId(),e.getEmpNom())).orElse(null)).filter(Objects::nonNull).toList();}
@Transactional public Salida crear(Entrada in){Long origen=contexto.empresaId();validar(origen,in);if(repo.findByEmpIdAndEmpresaRelacionadaIdAndTipo(origen,in.empresaRelacionadaId(),in.tipo()).isPresent())throw new IllegalArgumentException("La relación ya existe.");EmpresaRelacion a=nueva(origen,in.empresaRelacionadaId(),in.tipo(),in),b=nueva(in.empresaRelacionadaId(),origen,inverso(in.tipo()),in);a=repo.save(a);b=repo.save(b);a.setParejaId(b.getId());b.setParejaId(a.getId());repo.save(b);return salida(repo.save(a));}
@Transactional public Salida actualizar(Long id,Entrada in){EmpresaRelacion a=propia(id),b=pareja(a);validar(a.getEmpId(),in);a.setEmpresaRelacionadaId(in.empresaRelacionadaId());a.setTipo(in.tipo());copiar(a,in);b.setEmpId(in.empresaRelacionadaId());b.setEmpresaRelacionadaId(a.getEmpId());b.setTipo(inverso(in.tipo()));copiar(b,in);repo.save(b);return salida(repo.save(a));}
@Transactional public void eliminar(Long id){
 EmpresaRelacion a=propia(id),b=pareja(a);
 if(!Objects.equals(b.getParejaId(),a.getId())||!Objects.equals(b.getEmpId(),a.getEmpresaRelacionadaId())||!Objects.equals(b.getEmpresaRelacionadaId(),a.getEmpId())||!Objects.equals(b.getTipo(),inverso(a.getTipo())))throw new IllegalArgumentException("La relación inversa no es coherente. No se ha eliminado ninguna relación.");
 a.setParejaId(null);b.setParejaId(null);repo.saveAll(List.of(a,b));repo.flush();movimientos.deleteByRelacionId(a.getId());movimientos.deleteByRelacionId(b.getId());repo.deleteAll(List.of(a,b));
}
public List<EmpresaRelacionMovimiento> historico(Long id){EmpresaRelacion r=propia(id);return movimientos.findByEmpresaIdAndRelacionIdOrderByIdDesc(r.getEmpId(),id);}
@Transactional public void estado(Long id,boolean activa,String causa){
 if(causa==null||causa.trim().isEmpty()||causa.trim().length()>500)throw new IllegalArgumentException("Debe informar una causa de hasta 500 caracteres.");
 EmpresaRelacion a=propia(id),b=pareja(a);
 if(!Objects.equals(b.getParejaId(),a.getId())||!Objects.equals(b.getEmpId(),a.getEmpresaRelacionadaId())||!Objects.equals(b.getEmpresaRelacionadaId(),a.getEmpId())||!Objects.equals(b.getTipo(),inverso(a.getTipo())))throw new IllegalArgumentException("La relación inversa no es coherente.");
 if(Boolean.TRUE.equals(a.getActiva())==activa||!Objects.equals(a.getActiva(),b.getActiva()))throw new IllegalArgumentException("El estado de la relación no permite esta operación.");
 LocalDateTime fecha=contexto.fechaActual();String autor=contexto.nombreUsuario();
 for(EmpresaRelacion r:List.of(a,b)){
 r.setActiva(activa);r.setTipoMovimiento(activa?"R":"B");r.setCausaMovimiento(causa.trim());r.setUsuarioMovimiento(autor);r.setFechaMovimiento(fecha);repo.save(r);
 EmpresaRelacionMovimiento m=new EmpresaRelacionMovimiento();m.setEmpresaId(r.getEmpId());m.setRelacionId(r.getId());m.setTipo(r.getTipoMovimiento());m.setCausa(r.getCausaMovimiento());m.setUsuario(autor);m.setFecha(fecha);m.setActivo(activa);movimientos.save(m);
 }
}
private EmpresaRelacion nueva(Long emp,Long rel,String tipo,Entrada in){EmpresaRelacion r=new EmpresaRelacion();r.setEmpId(emp);r.setEmpresaRelacionadaId(rel);r.setTipo(tipo);copiar(r,in);movimiento(r,true);return r;}private void copiar(EmpresaRelacion r,Entrada in){r.setFechaInicio(in.fechaInicio());r.setFechaFin(in.fechaFin());r.setObservaciones(in.observaciones());r.setFechaMovimiento(LocalDateTime.now());r.setUsuarioMovimiento(usuario());}private void movimiento(EmpresaRelacion r,boolean activa){r.setActiva(activa);r.setFechaMovimiento(LocalDateTime.now());r.setUsuarioMovimiento(usuario());}private EmpresaRelacion propia(Long id){return repo.findById(id).filter(r->r.getEmpId().equals(contexto.empresaId())).orElseThrow(()->new IllegalArgumentException("Relación no encontrada."));}private EmpresaRelacion pareja(EmpresaRelacion a){return repo.findById(a.getParejaId()).orElseThrow(()->new IllegalArgumentException("Relación inversa no encontrada."));}private void validar(Long origen,Entrada in){if(origen.equals(in.empresaRelacionadaId()))throw new IllegalArgumentException("Una empresa no puede relacionarse consigo misma.");empresas.findById(in.empresaRelacionadaId()).orElseThrow(()->new IllegalArgumentException("Empresa relacionada no encontrada."));if(in.fechaInicio()!=null&&in.fechaFin()!=null&&in.fechaFin().isBefore(in.fechaInicio()))throw new IllegalArgumentException("La fecha fin no puede ser anterior a la fecha inicio.");}private String inverso(String t){return "PROVEEDOR".equals(t)?"CLIENTE":"PROVEEDOR";}private String usuario(){return contexto.usuarioActual().getUsername();}private Salida salida(EmpresaRelacion r){return new Salida(r.getId(),r.getEmpId(),nombre(r.getEmpId()),r.getTipo(),r.getEmpresaRelacionadaId(),nombre(r.getEmpresaRelacionadaId()),r.getParejaId(),r.getFechaInicio(),r.getFechaFin(),r.getObservaciones(),Boolean.TRUE.equals(r.getActiva()),r.getUsuarioMovimiento(),r.getFechaMovimiento(),r.getTipoMovimiento(),r.getCausaMovimiento(),movimientos.findByEmpresaIdAndRelacionIdOrderByIdDesc(r.getEmpId(),r.getId()).stream().findFirst().map(EmpresaRelacionMovimiento::getId).orElse(null));}private String nombre(Long id){return empresas.findById(id).map(Empresa::getEmpNom).orElse("Empresa "+id);}}
