package com.jbrempresa.backend.service;
import com.jbrempresa.backend.core.context.ContextoOperacion;import com.jbrempresa.backend.dto.mensajeria.MensajeriaDtos.*;import com.jbrempresa.backend.entity.ConversacionInterna;import com.jbrempresa.backend.entity.MensajeInterno;import com.jbrempresa.backend.entity.ParticipanteConversacionInterna;import com.jbrempresa.backend.entity.Usuario;import com.jbrempresa.backend.repository.*;import com.jbrempresa.backend.security.AccesoPerfilService;import jakarta.transaction.Transactional;import org.springframework.stereotype.Service;import java.time.LocalDate;import java.time.LocalDateTime;import java.time.LocalTime;import java.time.format.DateTimeFormatter;import java.util.*;
@Service public class MensajeriaInternaService{
 private final ConversacionInternaRepository conversaciones;private final ParticipanteConversacionInternaRepository participantes;private final MensajeInternoRepository mensajes;private final UsuarioRepository usuarios;private final PerfilRepository perfiles;private final ContextoOperacion contexto;private final AccesoPerfilService accesos;
 public MensajeriaInternaService(ConversacionInternaRepository a,ParticipanteConversacionInternaRepository b,MensajeInternoRepository c,UsuarioRepository d,PerfilRepository e,ContextoOperacion f,AccesoPerfilService g){conversaciones=a;participantes=b;mensajes=c;usuarios=d;perfiles=e;contexto=f;accesos=g;}
 public List<Destinatario> destinatarios(){var actual=contexto.usuarioActual();String rol=rolActual();return usuarios.findAll().stream().filter(u->!u.getUsuId().equals(actual.getUsuarioId())&&activo(u)&&permitido(u,rol)).map(this::destinatario).sorted(Comparator.comparing(Destinatario::nombre,String.CASE_INSENSITIVE_ORDER)).toList();}
 public List<Conversacion> conversaciones(){Long yo=id();return participantes.findByUsuarioIdAndActivaTrue(yo).stream().map(p->conversaciones.findById(p.getConversacionId()).filter(c->Boolean.TRUE.equals(c.getActiva())).map(c->salida(c,p)).orElse(null)).filter(Objects::nonNull).sorted(Comparator.comparing(Conversacion::fechaUltima).reversed()).toList();}
 public List<Conversacion> bajas(){exigirAdministrador();return conversaciones.findByActivaFalseOrderByFechaBajaDesc().stream().map(c->salida(c,null)).toList();}
 public List<Mensaje> mensajes(Long conversacionId,boolean marcarLeido){ConversacionInterna c=conversaciones.findById(conversacionId).orElseThrow(()->error("Conversación no encontrada."));ParticipanteConversacionInterna p=null;if(Boolean.TRUE.equals(c.getActiva()))p=participacion(conversacionId);else exigirAdministrador();List<MensajeInterno> lista=mensajes.findByConversacionIdAndActivoTrueOrderByFechaAsc(conversacionId);if(marcarLeido&&p!=null){p.setFechaLectura(LocalDateTime.now());participantes.save(p);}return lista.stream().map(this::salidaMensaje).toList();}
 @Transactional public Conversacion lectura(Long conversacionId,boolean leida){var p=participacion(conversacionId);p.setFechaLectura(leida?LocalDateTime.now():null);participantes.save(p);return salida(conversacionAccesible(conversacionId),p);}
 public long noLeidos(){Long yo=id();return participantes.findByUsuarioIdAndActivaTrue(yo).stream().filter(p->conversaciones.findById(p.getConversacionId()).map(c->Boolean.TRUE.equals(c.getActiva())).orElse(false)).mapToLong(p->noLeidos(p.getConversacionId(),p)).sum();}
 @Transactional public Conversacion crear(NuevaConversacion in){Set<Long> ids=new LinkedHashSet<>(in.destinatarioIds());if(ids.isEmpty())throw error("Seleccione al menos un destinatario.");Set<Long> validos=destinatarios().stream().map(Destinatario::usuarioId).collect(java.util.stream.Collectors.toSet());if(!validos.containsAll(ids))throw error("Alguno de los destinatarios no está permitido.");LocalDateTime ahora=LocalDateTime.now();ConversacionInterna c=new ConversacionInterna();c.setAsunto(in.asunto().trim());c.setFechaCreacion(ahora);c.setFechaUltima(ahora);c=conversaciones.save(c);ids.add(id());for(Long u:ids){ParticipanteConversacionInterna p=new ParticipanteConversacionInterna();p.setConversacionId(c.getId());p.setUsuarioId(u);p.setFechaLectura(u.equals(id())?ahora:null);participantes.save(p);}guardarMensaje(c,id(),in.contenido(),clasificacion(in.clasificacion()));return salida(c,participacion(c.getId()));}
 @Transactional public Mensaje responder(Long conversacionId,NuevoMensaje in){ConversacionInterna c=conversacionAccesible(conversacionId);MensajeInterno m=guardarMensaje(c,id(),in.contenido(),clasificacion(in.clasificacion()));ParticipanteConversacionInterna p=participacion(conversacionId);p.setFechaLectura(LocalDateTime.now());participantes.save(p);return salidaMensaje(m);}
 @Transactional public Mensaje editar(Long mensajeId,EditarMensaje in){exigirAdministrador();MensajeInterno m=mensajeAccesible(mensajeId);if(!m.getRemitenteId().equals(id()))throw error("Solo el remitente puede modificar el mensaje.");m.setContenido(in.contenido().trim());m.setFechaModificacion(LocalDateTime.now());return salidaMensaje(mensajes.save(m));}
 @Transactional public void darBaja(Long conversacionId){exigirAdministrador();ConversacionInterna c=conversacionAccesible(conversacionId);Usuario u=usuarios.findById(id()).orElseThrow();LocalDateTime ahora=LocalDateTime.now();guardarMensaje(c,id(),"Conversación dada de baja por "+nombre(u)+" en "+ahora.format(DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm")),"NORMAL");c.setActiva(false);c.setFechaBaja(ahora);c.setUsuarioBajaId(id());conversaciones.save(c);}
 @Transactional public Conversacion reactivar(Long conversacionId){exigirAdministrador();ConversacionInterna c=conversaciones.findById(conversacionId).filter(x->!Boolean.TRUE.equals(x.getActiva())).orElseThrow(()->error("Conversación dada de baja no encontrada."));c.setActiva(true);c.setFechaBaja(null);c.setUsuarioBajaId(null);return salida(conversaciones.save(c),null);}
 @Transactional public void eliminarDefinitivamente(Long conversacionId){exigirAdministrador();ConversacionInterna c=conversaciones.findById(conversacionId).filter(x->!Boolean.TRUE.equals(x.getActiva())).orElseThrow(()->error("Solo se pueden eliminar definitivamente conversaciones dadas de baja."));borrar(c);}
 @Transactional public int eliminarHasta(LocalDate fecha){exigirAdministrador();List<ConversacionInterna> lista=conversaciones.findByActivaFalseAndFechaBajaLessThanEqual(fecha.atTime(LocalTime.MAX));lista.forEach(this::borrar);return lista.size();}
 private MensajeInterno guardarMensaje(ConversacionInterna c,Long remitente,String contenido,String cla){LocalDateTime ahora=LocalDateTime.now();MensajeInterno m=new MensajeInterno();m.setConversacionId(c.getId());m.setRemitenteId(remitente);m.setContenido(contenido==null?"":contenido.trim());m.setClasificacion(cla);m.setFecha(ahora);c.setFechaUltima(ahora);conversaciones.save(c);return mensajes.save(m);}
 private Conversacion salida(ConversacionInterna c,ParticipanteConversacionInterna p){List<MensajeInterno> ms=mensajes.findByConversacionIdAndActivoTrueOrderByFechaAsc(c.getId());MensajeInterno ult=ms.isEmpty()?null:ms.get(ms.size()-1);List<Destinatario> todos=participantesDe(c.getId());String bajaPor=c.getUsuarioBajaId()==null?null:usuarios.findById(c.getUsuarioBajaId()).map(this::nombre).orElse("Usuario");return new Conversacion(c.getId(),c.getAsunto(),todos,ult==null?"":ult.getContenido(),ult==null?"":nombre(usuarios.findById(ult.getRemitenteId()).orElseThrow()),ult==null?List.of():destinatariosDe(c.getId(),ult.getRemitenteId()),ult==null?"NORMAL":ult.getClasificacion(),c.getFechaUltima(),p==null?0:noLeidos(c.getId(),p),Boolean.TRUE.equals(c.getActiva()),c.getFechaBaja(),bajaPor);}
 private long noLeidos(Long c,ParticipanteConversacionInterna p){LocalDateTime l=p.getFechaLectura();return mensajes.findByConversacionIdAndActivoTrueOrderByFechaAsc(c).stream().filter(m->!m.getRemitenteId().equals(id())&&(l==null||m.getFecha().isAfter(l))).count();}
 private Mensaje salidaMensaje(MensajeInterno m){Usuario u=usuarios.findById(m.getRemitenteId()).orElseThrow();return new Mensaje(m.getId(),m.getConversacionId(),m.getRemitenteId(),nombre(u),destinatariosDe(m.getConversacionId(),m.getRemitenteId()),m.getContenido(),m.getClasificacion(),m.getFecha(),m.getFechaModificacion(),m.getRemitenteId().equals(id()));}
 private List<Destinatario> participantesDe(Long conversacionId){return participantes.findByConversacionIdAndActivaTrue(conversacionId).stream().map(x->usuarios.findById(x.getUsuarioId()).map(this::destinatario).orElse(null)).filter(Objects::nonNull).toList();}
 private List<Destinatario> destinatariosDe(Long conversacionId,Long remitenteId){return participantesDe(conversacionId).stream().filter(d->!d.usuarioId().equals(remitenteId)).toList();}
 private void borrar(ConversacionInterna c){mensajes.deleteAll(mensajes.findByConversacionId(c.getId()));participantes.deleteAll(participantes.findByConversacionId(c.getId()));conversaciones.delete(c);}
 private void exigirAdministrador(){if(!"ADMINISTRADOR".equals(rolActual()))throw error("Acción reservada al administrador.");}
 private Destinatario destinatario(Usuario u){return new Destinatario(u.getUsuId(),u.getEmpId(),nombre(u),u.getUsuUsu(),rol(u));}
 private boolean permitido(Usuario u,String rol){String destino=rol(u);Long empresa=contexto.empresaSeleccionada();if("EMPLEADO".equals(rol))return "JEFE".equals(destino)&&Objects.equals(u.getEmpId(),contexto.usuarioActual().getEmpresaId());if("JEFE".equals(rol))return "ADMINISTRADOR".equals(destino)||("EMPLEADO".equals(destino)&&Objects.equals(u.getEmpId(),contexto.usuarioActual().getEmpresaId()));if("ADMINISTRADOR".equals(rol))return ("JEFE".equals(destino)||"EMPLEADO".equals(destino))&&(empresa==null||Objects.equals(empresa,u.getEmpId()));return false;}
 private String rolActual(){return accesos.perfil(contexto.usuarioActual()).getPerNom().trim().toUpperCase();}private String rol(Usuario u){return perfiles.findByEmpIdAndPerId(u.getEmpId(),u.getPerId()).map(x->x.getPerNom().trim().toUpperCase()).orElse("");}private boolean activo(Usuario u){return u.getUsuAct()!=null&&Set.of("TRUE","S","A","1").contains(u.getUsuAct().trim().toUpperCase())&&!"B".equalsIgnoreCase(u.getUsuTipMov());}private String nombre(Usuario u){return u.getUsuNom()==null||u.getUsuNom().isBlank()?u.getUsuUsu():u.getUsuNom();}private Long id(){return contexto.usuarioActual().getUsuarioId();}private String clasificacion(String v){return v==null||v.isBlank()?"NORMAL":v;}private ConversacionInterna conversacionAccesible(Long c){participacion(c);return conversaciones.findById(c).filter(x->Boolean.TRUE.equals(x.getActiva())).orElseThrow(()->error("Conversación no encontrada."));}private ParticipanteConversacionInterna participacion(Long c){return participantes.findByConversacionIdAndUsuarioIdAndActivaTrue(c,id()).orElseThrow(()->error("No tiene acceso a esta conversación."));}private MensajeInterno mensajeAccesible(Long m){MensajeInterno x=mensajes.findByIdAndActivoTrue(m).orElseThrow(()->error("Mensaje no encontrado."));participacion(x.getConversacionId());return x;}private IllegalArgumentException error(String m){return new IllegalArgumentException(m);}
}
