package com.jbrempresa.backend.entity;
import java.math.BigDecimal;import java.time.LocalDateTime;import jakarta.persistence.*;
@Entity @Table(name="caja_sesiones") public class CajaSesion{
 @Id @GeneratedValue(strategy=GenerationType.IDENTITY)@Column(name="cas_id")private Long casId;@Column(name="emp_id",nullable=false)private Long empId;@Column(name="caj_id",nullable=false)private Long cajId;
 @Column(name="cas_est",nullable=false,length=10)private String casEst;@Column(name="cas_fec_ape",nullable=false)private LocalDateTime casFecApe;@Column(name="cas_imp_ini",nullable=false)private BigDecimal casImpIni;
 @Column(name="cas_fec_cie")private LocalDateTime casFecCie;@Column(name="cas_imp_esp")private BigDecimal casImpEsp;@Column(name="cas_imp_con")private BigDecimal casImpCon;@Column(name="cas_imp_dif")private BigDecimal casImpDif;
 @Column(name="cas_obs",length=500)private String casObs;@Column(name="cas_usu_mov",nullable=false,length=100)private String casUsuMov;@Column(name="cas_fec_mov",nullable=false)private LocalDateTime casFecMov;
 public Long getCasId(){return casId;}public void setCasId(Long v){casId=v;}public Long getEmpId(){return empId;}public void setEmpId(Long v){empId=v;}public Long getCajId(){return cajId;}public void setCajId(Long v){cajId=v;}public String getCasEst(){return casEst;}public void setCasEst(String v){casEst=v;}public LocalDateTime getCasFecApe(){return casFecApe;}public void setCasFecApe(LocalDateTime v){casFecApe=v;}public BigDecimal getCasImpIni(){return casImpIni;}public void setCasImpIni(BigDecimal v){casImpIni=v;}public LocalDateTime getCasFecCie(){return casFecCie;}public void setCasFecCie(LocalDateTime v){casFecCie=v;}public BigDecimal getCasImpEsp(){return casImpEsp;}public void setCasImpEsp(BigDecimal v){casImpEsp=v;}public BigDecimal getCasImpCon(){return casImpCon;}public void setCasImpCon(BigDecimal v){casImpCon=v;}public BigDecimal getCasImpDif(){return casImpDif;}public void setCasImpDif(BigDecimal v){casImpDif=v;}public String getCasObs(){return casObs;}public void setCasObs(String v){casObs=v;}public String getCasUsuMov(){return casUsuMov;}public void setCasUsuMov(String v){casUsuMov=v;}public LocalDateTime getCasFecMov(){return casFecMov;}public void setCasFecMov(LocalDateTime v){casFecMov=v;}
}
