package com.jbrempresa.backend.entity;
import java.math.BigDecimal;import java.time.LocalDateTime;import jakarta.persistence.*;
@Entity @Table(name="caja_movimientos") public class CajaMovimiento{
 @Id @GeneratedValue(strategy=GenerationType.IDENTITY)@Column(name="cam_id")private Long camId;@Column(name="emp_id",nullable=false)private Long empId;@Column(name="cas_id",nullable=false)private Long casId;
 @Column(name="cam_tip",nullable=false,length=20)private String camTip;@Column(name="cam_med",nullable=false,length=20)private String camMed;@Column(name="cam_imp",nullable=false)private BigDecimal camImp;@Column(name="cam_con",nullable=false,length=200)private String camCon;
 @Column(name="per_id")private Long perId;@Column(name="dov_id")private Long dovId;@Column(name="cam_obs",length=500)private String camObs;@Column(name="cam_act",nullable=false)private Boolean camAct;
 @Column(name="cam_usu_mov",nullable=false,length=100)private String camUsuMov;@Column(name="cam_fec_mov",nullable=false)private LocalDateTime camFecMov;
 public Long getCamId(){return camId;}public void setCamId(Long v){camId=v;}public Long getEmpId(){return empId;}public void setEmpId(Long v){empId=v;}public Long getCasId(){return casId;}public void setCasId(Long v){casId=v;}public String getCamTip(){return camTip;}public void setCamTip(String v){camTip=v;}public String getCamMed(){return camMed;}public void setCamMed(String v){camMed=v;}public BigDecimal getCamImp(){return camImp;}public void setCamImp(BigDecimal v){camImp=v;}public String getCamCon(){return camCon;}public void setCamCon(String v){camCon=v;}public Long getPerId(){return perId;}public void setPerId(Long v){perId=v;}public Long getDovId(){return dovId;}public void setDovId(Long v){dovId=v;}public String getCamObs(){return camObs;}public void setCamObs(String v){camObs=v;}public Boolean getCamAct(){return camAct;}public void setCamAct(Boolean v){camAct=v;}public String getCamUsuMov(){return camUsuMov;}public void setCamUsuMov(String v){camUsuMov=v;}public LocalDateTime getCamFecMov(){return camFecMov;}public void setCamFecMov(LocalDateTime v){camFecMov=v;}
}
