package com.jbrempresa.backend.entity;
import com.fasterxml.jackson.annotation.JsonFormat;
import jakarta.persistence.*;
import java.math.BigDecimal;import java.time.LocalDate;import java.time.LocalDateTime;import java.util.ArrayList;import java.util.List;
@Entity @Table(name="documentos_venta")
public class DocumentoVenta{
 @Id @GeneratedValue(strategy=GenerationType.IDENTITY) @Column(name="dov_id") private Long dovId;
 @Column(name="emp_id",nullable=false) private Long empId; @Column(name="dov_tip",nullable=false,length=3) private String dovTip; @Column(name="dov_num",nullable=false,length=30) private String dovNum; @Column(name="per_id",nullable=false) private Long perId;
 @Column(name="dov_fec",nullable=false) private LocalDate dovFec; @Column(name="dov_est",nullable=false,length=20) private String dovEst; @Column(name="dov_id_ori") private Long dovIdOri; @Column(name="dov_id_rai") private Long dovIdRai;
 @Column(name="dov_ubi",length=100) private String dovUbi; @Column(name="dov_ori",length=20) private String dovOri; @Column(name="dov_mod",length=20) private String dovMod; @Column(name="dov_dir_env",length=500) private String dovDirEnv; @Column(name="dov_fil_mal") private Integer dovFilMal; @Column(name="dov_col_mal") private Integer dovColMal;
 @Column(name="dov_imp_sub") private BigDecimal dovImpSub; @Column(name="dov_imp_des") private BigDecimal dovImpDes; @Column(name="dov_imp_iva") private BigDecimal dovImpIva; @Column(name="dov_imp_tot") private BigDecimal dovImpTot; @Column(name="dov_obs",length=500) private String dovObs;
 @Column(name="dov_usu_mov",nullable=false,length=100) private String dovUsuMov; @JsonFormat(pattern="dd/MM/yyyy HH:mm:ss") @Column(name="dov_fec_mov",nullable=false) private LocalDateTime dovFecMov; @Column(name="dov_act",nullable=false) private Boolean dovAct;
 @Transient private List<DocumentoVentaDetalle> detalles=new ArrayList<>();
 public Long getDovId(){return dovId;}public void setDovId(Long v){dovId=v;}public Long getEmpId(){return empId;}public void setEmpId(Long v){empId=v;}public String getDovTip(){return dovTip;}public void setDovTip(String v){dovTip=v;}public String getDovNum(){return dovNum;}public void setDovNum(String v){dovNum=v;}public Long getPerId(){return perId;}public void setPerId(Long v){perId=v;}public LocalDate getDovFec(){return dovFec;}public void setDovFec(LocalDate v){dovFec=v;}public String getDovEst(){return dovEst;}public void setDovEst(String v){dovEst=v;}public Long getDovIdOri(){return dovIdOri;}public void setDovIdOri(Long v){dovIdOri=v;}public Long getDovIdRai(){return dovIdRai;}public void setDovIdRai(Long v){dovIdRai=v;}public String getDovUbi(){return dovUbi;}public void setDovUbi(String v){dovUbi=v;}public String getDovOri(){return dovOri;}public void setDovOri(String v){dovOri=v;}public String getDovMod(){return dovMod;}public void setDovMod(String v){dovMod=v;}public String getDovDirEnv(){return dovDirEnv;}public void setDovDirEnv(String v){dovDirEnv=v;}public Integer getDovFilMal(){return dovFilMal;}public void setDovFilMal(Integer v){dovFilMal=v;}public Integer getDovColMal(){return dovColMal;}public void setDovColMal(Integer v){dovColMal=v;}public BigDecimal getDovImpSub(){return dovImpSub;}public void setDovImpSub(BigDecimal v){dovImpSub=v;}public BigDecimal getDovImpDes(){return dovImpDes;}public void setDovImpDes(BigDecimal v){dovImpDes=v;}public void setDovImpIva(BigDecimal v){dovImpIva=v;}public BigDecimal getDovImpIva(){return dovImpIva;}public BigDecimal getDovImpTot(){return dovImpTot;}public void setDovImpTot(BigDecimal v){dovImpTot=v;}public String getDovObs(){return dovObs;}public void setDovObs(String v){dovObs=v;}public String getDovUsuMov(){return dovUsuMov;}public void setDovUsuMov(String v){dovUsuMov=v;}public LocalDateTime getDovFecMov(){return dovFecMov;}public void setDovFecMov(LocalDateTime v){dovFecMov=v;}public Boolean getDovAct(){return dovAct;}public void setDovAct(Boolean v){dovAct=v;}public List<DocumentoVentaDetalle> getDetalles(){return detalles;}public void setDetalles(List<DocumentoVentaDetalle> v){detalles=v;}
}
