package com.jbrempresa.backend.entity;
import jakarta.persistence.*;import java.time.*;
@Entity@Table(name="empresas_relaciones",uniqueConstraints=@UniqueConstraint(columnNames={"emp_id","ere_emp_rel_id","ere_tip"}))
public class EmpresaRelacion{@Id@GeneratedValue(strategy=GenerationType.IDENTITY)@Column(name="ere_id")private Long id;@Column(name="emp_id",nullable=false)private Long empId;@Column(name="ere_emp_rel_id",nullable=false)private Long empresaRelacionadaId;@Column(name="ere_tip",nullable=false,length=20)private String tipo;@Column(name="ere_par_id")private Long parejaId;@Column(name="ere_fec_ini")private LocalDate fechaInicio;@Column(name="ere_fec_fin")private LocalDate fechaFin;@Column(name="ere_obs",length=500)private String observaciones;@Column(name="ere_act",nullable=false)private Boolean activa=true;@Column(name="ere_usu_mov",nullable=false,length=100)private String usuarioMovimiento;@Column(name="ere_fec_mov",nullable=false)private LocalDateTime fechaMovimiento;
@Column(name="ere_tip_mov",length=1)private String tipoMovimiento;
@Column(name="ere_cau_mov",length=500)private String causaMovimiento;
public String getTipoMovimiento(){return tipoMovimiento;}public void setTipoMovimiento(String v){tipoMovimiento=v;}
public String getCausaMovimiento(){return causaMovimiento;}public void setCausaMovimiento(String v){causaMovimiento=v;}
public Long getId(){return id;}public Long getEmpId(){return empId;}public void setEmpId(Long v){empId=v;}public Long getEmpresaRelacionadaId(){return empresaRelacionadaId;}public void setEmpresaRelacionadaId(Long v){empresaRelacionadaId=v;}public String getTipo(){return tipo;}public void setTipo(String v){tipo=v;}public Long getParejaId(){return parejaId;}public void setParejaId(Long v){parejaId=v;}public LocalDate getFechaInicio(){return fechaInicio;}public void setFechaInicio(LocalDate v){fechaInicio=v;}public LocalDate getFechaFin(){return fechaFin;}public void setFechaFin(LocalDate v){fechaFin=v;}public String getObservaciones(){return observaciones;}public void setObservaciones(String v){observaciones=v;}public Boolean getActiva(){return activa;}public void setActiva(Boolean v){activa=v;}public String getUsuarioMovimiento(){return usuarioMovimiento;}public void setUsuarioMovimiento(String v){usuarioMovimiento=v;}public LocalDateTime getFechaMovimiento(){return fechaMovimiento;}public void setFechaMovimiento(LocalDateTime v){fechaMovimiento=v;}}
