import {BarraAcciones} from '../../../directives/barraAcciones/barraAcciones';
import {avisarAplicacion,confirmarAplicacion} from '../../../core/interaccion/dialogos.service';
import { DatosIdentificacion } from '../../../components/datosIdentificacion/datosIdentificacion';
import { DatosMovimiento } from '../../../components/datosMovimiento/datosMovimiento';
import {CommonModule} from '@angular/common';import {Component} from '@angular/core';import {FormsModule} from '@angular/forms';import {ActivatedRoute,Router} from '@angular/router';import {Sidebar} from '../../../components/sidebar/sidebar';import {Supbar} from '../../../components/supbar/supbar';import {Tabla} from '../../../components/tabla/tabla';import {DatosPersonaRelacion} from '../../../components/datosPersonaRelacion/datosPersonaRelacion';import {Caja,CajaMovimiento,CajaSesion} from '../../../interfaces/caja.interface';import {Persona} from '../../../interfaces/persona.interface';import {CajaService} from '../../../services/caja.service';import {PersonaService} from '../../../services/persona.service';
@Component({selector:'Cajas',standalone:true,imports:[CommonModule,FormsModule,Sidebar,Supbar,Tabla,DatosPersonaRelacion,DatosIdentificacion,DatosMovimiento,BarraAcciones],templateUrl:'./cajas.html',styleUrl:'../../../styles/estiloGeneral.css'}) export class Cajas{
 gestion=false;vista:'tabla'|'registro'|'sesion'='tabla';modo:'insertar'|'modificar'|'ver'='insertar';datos:Caja[]=[];sesiones:CajaSesion[]=[];movimientos:CajaMovimiento[]=[];personas:Persona[]=[];seleccion:Caja|null=null;caja=this.vacia();sesion:CajaSesion|null=null;importeInicial=0;importeContado=0;observaciones='';movimiento=this.movVacio();columnas=['empId','cajId','cajNom','cajDes','cajAct','cajUsuMov','cajFecMov'];titulos:any={empId:'Empresa',cajId:'Caja',cajNom:'Nombre',cajDes:'Descripción',cajAct:'Activa',cajUsuMov:'Usuario Mod.',cajFecMov:'Fecha Mod.'};columnasSes=['casId','cajaNom','casEst','casFecApe','casFecCie','casImpIni','casImpEsp','casImpCon','casImpDif'];titulosSes:any={casId:'Sesión',cajaNom:'Caja',casEst:'Estado',casFecApe:'Apertura',casFecCie:'Cierre',casImpIni:'Importe inicial',casImpEsp:'Esperado',casImpCon:'Contado',casImpDif:'Diferencia'};columnasMov=['camId','camTip','camMed','camImp','camCon','personaNomCom','dovId','camFecMov'];titulosMov:any={camId:'Movimiento',camTip:'Tipo',camMed:'Medio',camImp:'Importe',camCon:'Concepto',personaNomCom:'Persona',dovId:'Documento venta',camFecMov:'Fecha'};
 observacionesApertura='';observacionesCierre='';movimientoSeleccionado:CajaMovimiento|null=null;
 constructor(private api:CajaService,private personaApi:PersonaService,route:ActivatedRoute,private router:Router){this.gestion=!!route.snapshot.data['gestion'];personaApi.obtenerPersonasSelector().subscribe({next:x=>this.personas=x,error:e=>this.errorContexto('No se pudieron cargar las personas.',e)});this.cargar()}
 cargar(){this.vista='tabla';this.seleccion=null;this.api.cajas().subscribe({next:x=>{this.datos=x;if(this.gestion)this.cargarSesiones()},error:e=>this.errorContexto('No se pudieron consultar las cajas.',e)})}cargarSesiones(){this.api.sesiones().subscribe({next:x=>this.sesiones=x.map(s=>({...s,cajaNom:this.datos.find(c=>c.cajId===s.cajId)?.cajNom||''})),error:e=>this.errorContexto('No se pudieron consultar las sesiones de caja.',e)})}
 insertar(){this.modo='insertar';this.caja=this.vacia();this.vista='registro'}ver(){if(this.seleccion){this.modo='ver';this.caja={...this.seleccion};this.vista='registro'}}modificar(){if(this.seleccion){this.modo='modificar';this.caja={...this.seleccion};this.vista='registro'}}guardar(){if(!this.caja.cajNom.trim()){avisarAplicacion('El nombre es obligatorio.');return}const op=this.modo==='insertar'?this.api.crear(this.caja):this.api.actualizar(this.caja);op.subscribe({next:()=>this.cargar(),error:e=>this.error(e)})}async eliminar(){if(this.seleccion&&await confirmarAplicacion('¿Eliminar definitivamente la caja seleccionada?',true))this.api.eliminar(this.seleccion.cajId!).subscribe({next:()=>this.cargar(),error:e=>this.error(e)})}async estado(){if(this.seleccion&&await confirmarAplicacion(this.seleccion.cajAct?'¿Dar de baja la caja?':'¿Reactivar la caja?',true))this.api.estado(this.seleccion.cajId!,!this.seleccion.cajAct).subscribe({next:()=>this.cargar(),error:e=>this.error(e)})}
 sesionAbierta(c:Caja){return this.sesiones.find(s=>s.cajId===c.cajId&&s.casEst==='ABIERTA')}abrir(){if(!this.seleccion)return;if(this.importeInicial<0){avisarAplicacion('El importe inicial no puede ser negativo.');return}this.api.abrir(this.seleccion.cajId!,this.importeInicial,this.observacionesApertura).subscribe({next:s=>{this.sesion=s;this.importeInicial=0;this.observacionesApertura='';this.abrirSesion(s)},error:e=>this.errorContexto('No se pudo abrir la caja.',e)})}gestionar(){if(!this.seleccion)return;const s=this.sesionAbierta(this.seleccion);if(s)this.abrirSesion(s);else{this.sesion=null;this.movimientos=[];this.vista='sesion'}}abrirSesion(s:CajaSesion){this.sesion=s;this.movimientoSeleccionado=null;this.api.movimientos(s.casId).subscribe({next:x=>{this.movimientos=this.enriquecer(x);this.movimiento=this.movVacio();this.vista='sesion'},error:e=>this.errorContexto('No se pudieron consultar los movimientos de la sesión.',e)})}registrarMovimiento(){if(!this.sesion)return;if(!this.movimiento.camCon.trim()||this.movimiento.camImp<=0){avisarAplicacion('Concepto e importe positivo son obligatorios.');return}this.api.movimiento(this.sesion.casId,this.movimiento).subscribe({next:()=>this.abrirSesion(this.sesion!),error:e=>this.errorContexto('No se pudo registrar el movimiento.',e)})}async cerrar(){if(!this.sesion)return;if(this.importeContado<0){avisarAplicacion('El importe contado no puede ser negativo.');return}if(await confirmarAplicacion('¿Cerrar la sesión de caja?',true))this.api.cerrar(this.sesion.casId,this.importeContado,this.observacionesCierre).subscribe({next:()=>{this.observacionesCierre='';this.cargar()},error:e=>this.errorContexto('No se pudo cerrar la caja.',e)})}async anularSeleccionado(){const m=this.movimientoSeleccionado;if(m?.camId&&await confirmarAplicacion('¿Anular el movimiento seleccionado?',true))this.api.anular(m.camId).subscribe({next:()=>this.abrirSesion(this.sesion!),error:e=>this.errorContexto('No se pudo anular el movimiento.',e)})}
 nombrePersona(id:number|null){return this.personas.find(p=>Number(p.perId)===Number(id))?.perNomCom||''}enriquecer(x:CajaMovimiento[]){return x.map(m=>({...m,personaNomCom:this.nombrePersona(m.perId)}))}vacia():Caja{return{empId:Number(localStorage.getItem('empresaId'))||0,cajId:null,cajNom:'',cajDes:'',cajAct:true}}movVacio():CajaMovimiento{return{camId:null,empId:Number(localStorage.getItem('empresaId'))||0,casId:this.sesion?.casId||0,camTip:'COBRO',camMed:'EFECTIVO',camImp:0,camCon:'',perId:null,dovId:null,camObs:'',camAct:true}}volver(){this.router.navigate(['/caja'])}error(e:any){this.errorContexto('No se pudo completar la operación.',e)}errorContexto(contexto:string,e:any){console.error(contexto,e);avisarAplicacion(e?.error?.detail||e?.error?.message||contexto)}
}
