import { Tabla } from '../../../components/tabla/tabla';
import { BarraAcciones } from '../../../directives/barraAcciones/barraAcciones';
import { formatDate } from '@angular/common';
import{CommonModule}from'@angular/common';import{Component,OnInit}from'@angular/core';import{FormsModule}from'@angular/forms';import{ActivatedRoute,Router}from'@angular/router';import{Supbar}from'../../../components/supbar/supbar';import{Sidebar}from'../../../components/sidebar/sidebar';import{DatosIdentificacion}from'../../../components/datosIdentificacion/datosIdentificacion';import{DatosMovimiento}from'../../../components/datosMovimiento/datosMovimiento';import{EmpresaRelacion,EmpresaRelacionEntrada,OpcionEmpresa,TipoRelacionEmpresa}from'../../../interfaces/empresa-relacion.interface';import{EmpresaRelacionService}from'../../../services/empresa-relacion.service';import{DialogosService}from'../../../core/interaccion/dialogos.service';
@Component({selector:'relaciones-empresa',standalone:true,imports:[CommonModule,FormsModule,Supbar,Sidebar,DatosIdentificacion,DatosMovimiento,Tabla,BarraAcciones],templateUrl:'./relacionesEmpresa.html',styleUrls:['../../../styles/estiloGeneral.css','./relacionesEmpresa.css']})export class RelacionesEmpresa implements OnInit{readonly columnasBase = ['empId','empresa','id','empresaRelacionadaId','empresaRelacionada','tipo','parejaId','fechaInicio','fechaFin','observaciones','usuarioMovimiento','fechaMovimiento','activa'];
get columnas(){return this.gestion?[...this.columnasBase,'idHistorico','tipoMovimiento','causaMovimiento']:this.columnasBase;}
get identificacion(){const campos=[{etiqueta:'Id Empresa',valor:this.seleccion?.empId||0},{etiqueta:'Id Relación',valor:this.seleccion?.id||0}];if(this.gestion)campos.push({etiqueta:'Id Histórico',valor:this.seleccion?.idHistorico||0});return campos;}
historicoDatos: Record<string,unknown>[]=[];
readonly historicoColumnas=['id','empresaId','relacionId','tipo','causa','usuario','fecha','activo'];
readonly historicoTitulos={id:'Id Histórico',empresaId:'Id Empresa',relacionId:'Id Relación',tipo:'Tipo',causa:'Causa',usuario:'Usuario',fecha:'Fecha',activo:'Activo'};
verHistorico(){if(!this.gestion||!this.seleccion)return;this.api.historico(this.seleccion.id).subscribe({next:r=>{this.historicoDatos=r.map(m=>({...m,fecha:formatDate(m.fecha,'dd/MM/yyyy HH:mm:ss','en-US'),activo:m.activo?'Sí':'No'}));this.vista='historico';},error:e=>this.dialogos.error(e)});}
readonly columnasOcultas = ['empresaRelacionadaId','parejaId'];
readonly titulosColumnas: Record<string,string> = {empId:'Id Empresa',empresa:'Empresa',id:'Id Relación',empresaRelacionadaId:'Id Empresa relacionada',empresaRelacionada:'Empresa relacionada',tipo:'Tipo',parejaId:'Id pareja',fechaInicio:'Fecha inicio',fechaFin:'Fecha fin',observaciones:'Observaciones',usuarioMovimiento:'Usuario',fechaMovimiento:'Fecha',activa:'Activo',idHistorico:'Id Histórico',tipoMovimiento:'Tipo Movimiento',causaMovimiento:'Causa Movimiento'};
filas: Record<string,unknown>[] = [];
seleccionarFila(fila: {id:number}) { this.seleccion = this.datos.find(r => r.id === fila.id); }
private actualizarDatos(datos: EmpresaRelacion[]) {
 this.datos = datos;
 this.filas = datos.map(r => ({...r, tipo:r.tipo==='PROVEEDOR'?'Proveedor':'Cliente', activa:r.activa?'Sí':'No', fechaInicio:r.fechaInicio?formatDate(r.fechaInicio,'dd/MM/yyyy','en-US'):'',fechaFin:r.fechaFin?formatDate(r.fechaFin,'dd/MM/yyyy','en-US'):'',fechaMovimiento:r.fechaMovimiento?formatDate(r.fechaMovimiento,'dd/MM/yyyy HH:mm:ss','en-US'):''}));
}
gestion=false;vista:'tabla'|'formulario'|'historico'='tabla';modo:'insertar'|'ver'|'modificar'='ver';datos:EmpresaRelacion[]=[];empresas:OpcionEmpresa[]=[];seleccion?:EmpresaRelacion;form:EmpresaRelacionEntrada={empresaRelacionadaId:0,tipo:'PROVEEDOR',fechaInicio:null,fechaFin:null,observaciones:''};constructor(private api:EmpresaRelacionService,private ruta:ActivatedRoute,private router:Router,private dialogos:DialogosService){}ngOnInit(){this.gestion=!!this.ruta.snapshot.data['gestion'];this.api.empresas().subscribe({next:r=>this.empresas=r,error:e=>this.dialogos.error(e)});}consultar(){this.vista='tabla';this.seleccion=undefined;this.api.listar().subscribe({next:r=>this.actualizarDatos(r),error:e=>this.dialogos.error(e)});}insertar(){this.form={empresaRelacionadaId:0,tipo:'PROVEEDOR',fechaInicio:new Date().toISOString().slice(0,10),fechaFin:null,observaciones:''};this.modo='insertar';this.vista='formulario';}ver(m:'ver'|'modificar'='ver'){if(!this.seleccion)return;this.form={empresaRelacionadaId:this.seleccion.empresaRelacionadaId,tipo:this.seleccion.tipo,fechaInicio:this.seleccion.fechaInicio,fechaFin:this.seleccion.fechaFin,observaciones:this.seleccion.observaciones||''};this.modo=m;this.vista='formulario';}guardar(){if(!this.form.empresaRelacionadaId){this.dialogos.avisar('Seleccione la empresa relacionada.');return;}const peticion=this.modo==='insertar'?this.api.crear(this.form):this.api.actualizar(this.seleccion!.id,this.form);peticion.subscribe({next:()=>{this.dialogos.exito('Relación y relación inversa guardadas.');this.consultar();},error:e=>this.dialogos.error(e)});}async eliminar(){
 if(this.gestion||!this.seleccion)return;
 const relacion=this.seleccion;
 if(!await this.dialogos.confirmar('¿Eliminar definitivamente la relación entre '+relacion.empresa+' y '+relacion.empresaRelacionada+' y su relación inversa?',true))return;
 this.api.eliminar(relacion.id).subscribe({next:()=>{this.consultar();this.dialogos.exito('Relación y relación inversa eliminadas.');},error:e=>this.dialogos.error(e)});
}
async baja(){await this.cambiarEstado(false);}async reactivar(){await this.cambiarEstado(true);}
private async cambiarEstado(activa:boolean){if(!this.gestion||!this.seleccion)return;const id=this.seleccion.id;const causa=await this.dialogos.solicitarTexto('Indique la causa. La operación afecta también a la relación inversa.',activa?'Reactivar relación':'Dar de baja relación');if(causa===null)return;if(!causa.trim()||causa.trim().length>500){this.dialogos.avisar('Debe informar una causa de hasta 500 caracteres.');return;}const pet=activa?this.api.reactivar(id,causa.trim()):this.api.baja(id,causa.trim());pet.subscribe({next:()=>this.consultar(),error:e=>this.dialogos.error(e)});}
volver(){this.router.navigate(['/administracion']);}}
