-- Los nombres de tipo se presentan siempre en plural y se actualizan en todas
-- las relaciones que los almacenan como código textual.
UPDATE tipos_articulo SET tia_nom = CASE UPPER(tia_nom)
 WHEN 'BOCADILLO' THEN 'BOCADILLOS' WHEN 'HAMBURGUESA' THEN 'HAMBURGUESAS'
 WHEN 'PIZZA' THEN 'PIZZAS' WHEN 'REPUESTO' THEN 'REPUESTOS'
 WHEN 'BEBIDA' THEN 'BEBIDAS' WHEN 'CARNE' THEN 'CARNES'
 WHEN 'ENTRANTE' THEN 'ENTRANTES' WHEN 'PASTA' THEN 'PASTAS'
 WHEN 'PESCADO' THEN 'PESCADOS' WHEN 'POSTRE' THEN 'POSTRES'
 WHEN 'VINO' THEN 'VINOS' WHEN 'REPARTO' THEN 'REPARTOS'
 WHEN 'TALLER' THEN 'TALLERES' WHEN 'MENU_DEGUSTACION' THEN 'MENUS_DEGUSTACION'
 WHEN 'RESERVA_MESA' THEN 'RESERVAS_MESA' ELSE tia_nom END;

UPDATE productos SET pro_tip_pro = CASE UPPER(pro_tip_pro)
 WHEN 'BOCADILLO' THEN 'BOCADILLOS' WHEN 'HAMBURGUESA' THEN 'HAMBURGUESAS'
 WHEN 'PIZZA' THEN 'PIZZAS' WHEN 'REPUESTO' THEN 'REPUESTOS'
 WHEN 'BEBIDA' THEN 'BEBIDAS' WHEN 'CARNE' THEN 'CARNES'
 WHEN 'ENTRANTE' THEN 'ENTRANTES' WHEN 'PASTA' THEN 'PASTAS'
 WHEN 'PESCADO' THEN 'PESCADOS' WHEN 'POSTRE' THEN 'POSTRES'
 WHEN 'VINO' THEN 'VINOS' ELSE pro_tip_pro END;

UPDATE servicios SET ser_tip_ser = CASE UPPER(ser_tip_ser)
 WHEN 'REPARTO' THEN 'REPARTOS' WHEN 'TALLER' THEN 'TALLERES'
 WHEN 'MENU_DEGUSTACION' THEN 'MENUS_DEGUSTACION'
 WHEN 'RESERVA_MESA' THEN 'RESERVAS_MESA' ELSE ser_tip_ser END;

UPDATE recursos_capacidades SET rec_tip = CASE
 WHEN rec_ori='PRODUCTO' THEN CASE UPPER(rec_tip)
  WHEN 'BOCADILLO' THEN 'BOCADILLOS' WHEN 'HAMBURGUESA' THEN 'HAMBURGUESAS'
  WHEN 'PIZZA' THEN 'PIZZAS' WHEN 'REPUESTO' THEN 'REPUESTOS'
  WHEN 'BEBIDA' THEN 'BEBIDAS' WHEN 'CARNE' THEN 'CARNES'
  WHEN 'ENTRANTE' THEN 'ENTRANTES' WHEN 'PASTA' THEN 'PASTAS'
  WHEN 'PESCADO' THEN 'PESCADOS' WHEN 'POSTRE' THEN 'POSTRES'
  WHEN 'VINO' THEN 'VINOS' ELSE rec_tip END
 WHEN rec_ori='SERVICIO' THEN CASE UPPER(rec_tip)
  WHEN 'REPARTO' THEN 'REPARTOS' WHEN 'TALLER' THEN 'TALLERES'
  WHEN 'MENU_DEGUSTACION' THEN 'MENUS_DEGUSTACION'
  WHEN 'RESERVA_MESA' THEN 'RESERVAS_MESA' ELSE rec_tip END
 ELSE rec_tip END;
