ALTER TABLE productos ADD COLUMN IF NOT EXISTS pro_dis_lun BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE productos ADD COLUMN IF NOT EXISTS pro_dis_mar BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE productos ADD COLUMN IF NOT EXISTS pro_dis_mie BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE productos ADD COLUMN IF NOT EXISTS pro_dis_jue BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE productos ADD COLUMN IF NOT EXISTS pro_dis_vie BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE productos ADD COLUMN IF NOT EXISTS pro_dis_sab BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE productos ADD COLUMN IF NOT EXISTS pro_dis_dom BOOLEAN NOT NULL DEFAULT TRUE;

DROP TABLE IF EXISTS ingredientes;

CREATE TABLE IF NOT EXISTS componentes (
 emp_id BIGINT NOT NULL, cmp_id BIGINT NOT NULL, cmp_id_his BIGINT NOT NULL,
 cmp_tip_mov VARCHAR(1) NOT NULL, cmp_cau_mov VARCHAR(500), cmp_tip VARCHAR(30) NOT NULL DEFAULT 'INGREDIENTE', cmp_nom VARCHAR(80) NOT NULL,
 cmp_des VARCHAR(200), cmp_pre_adi NUMERIC(14,4) NOT NULL DEFAULT 0, cmp_iva NUMERIC(5,2) NOT NULL DEFAULT 0,
 cmp_gluten BOOLEAN NOT NULL DEFAULT FALSE, cmp_crustaceos BOOLEAN NOT NULL DEFAULT FALSE,
 cmp_huevos BOOLEAN NOT NULL DEFAULT FALSE, cmp_pescado BOOLEAN NOT NULL DEFAULT FALSE,
 cmp_cacahuetes BOOLEAN NOT NULL DEFAULT FALSE, cmp_soja BOOLEAN NOT NULL DEFAULT FALSE,
 cmp_leche BOOLEAN NOT NULL DEFAULT FALSE, cmp_frutos_cascara BOOLEAN NOT NULL DEFAULT FALSE,
 cmp_apio BOOLEAN NOT NULL DEFAULT FALSE, cmp_mostaza BOOLEAN NOT NULL DEFAULT FALSE,
 cmp_sesamo BOOLEAN NOT NULL DEFAULT FALSE, cmp_sulfitos BOOLEAN NOT NULL DEFAULT FALSE,
 cmp_altramuces BOOLEAN NOT NULL DEFAULT FALSE, cmp_moluscos BOOLEAN NOT NULL DEFAULT FALSE,
 cmp_usu_mov VARCHAR(100) NOT NULL, cmp_fec_mov TIMESTAMP NOT NULL, cmp_act BOOLEAN NOT NULL,
 PRIMARY KEY (emp_id, cmp_id, cmp_id_his)
);
CREATE INDEX IF NOT EXISTS idx_componentes_empresa_activo ON componentes(emp_id, cmp_act);
