BEGIN;
ALTER TABLE compras ADD COLUMN IF NOT EXISTS com_proveedor_emp_id bigint;
ALTER TABLE compras ADD COLUMN IF NOT EXISTS com_pedido_venta_id bigint;
ALTER TABLE compras ADD COLUMN IF NOT EXISTS com_pedido_venta_num varchar(255);
ALTER TABLE compras ADD COLUMN IF NOT EXISTS com_proveedor_nombre varchar(255);
CREATE UNIQUE INDEX IF NOT EXISTS uk_compra_pedido_proveedor
    ON compras (com_proveedor_emp_id, com_pedido_venta_id);
CREATE TABLE IF NOT EXISTS compras_detalle (
    com_det_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id bigint NOT NULL, com_id bigint NOT NULL, pro_id bigint,
    com_det_can integer NOT NULL, com_det_pre numeric(38,2) NOT NULL,
    com_det_des numeric(38,2) NOT NULL, com_det_iva numeric(38,2) NOT NULL,
    com_det_imp numeric(38,2) NOT NULL, com_det_usu_mov varchar(255) NOT NULL,
    com_det_fec_mov timestamp NOT NULL, com_det_act boolean NOT NULL
);
ALTER TABLE compras_detalle ALTER COLUMN pro_id DROP NOT NULL;
ALTER TABLE compras_detalle ADD COLUMN IF NOT EXISTS ser_id bigint;
ALTER TABLE compras_detalle ADD COLUMN IF NOT EXISTS com_det_nom varchar(200);
ALTER TABLE compras_detalle ADD COLUMN IF NOT EXISTS com_det_obs varchar(250);
COMMIT;
