ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS usu_tip_mov VARCHAR(1);
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS usu_cau_mov VARCHAR(500);
CREATE TABLE IF NOT EXISTS usuarios_movimientos(usm_id BIGSERIAL PRIMARY KEY,emp_id BIGINT NOT NULL,usu_id BIGINT NOT NULL,usm_tip VARCHAR(1) NOT NULL CHECK(usm_tip IN('B','R')),usm_cau VARCHAR(500) NOT NULL,usm_usu VARCHAR(100) NOT NULL,usm_fec TIMESTAMP NOT NULL,usm_act BOOLEAN NOT NULL);
