CREATE TABLE IF NOT EXISTS recuperaciones_contrasena (
    rec_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cli_id BIGINT NOT NULL,
    usu_id BIGINT NOT NULL,
    rec_tok_hash VARCHAR(64) NOT NULL UNIQUE,
    rec_fec_cre TIMESTAMP NOT NULL,
    rec_fec_exp TIMESTAMP NOT NULL,
    rec_fec_uso TIMESTAMP NULL,
    rec_usu_mov VARCHAR(100) NOT NULL,
    rec_fec_mov TIMESTAMP NOT NULL,
    rec_act BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_recuperacion_usuario FOREIGN KEY (usu_id) REFERENCES usuarios (usu_id)
);

CREATE INDEX IF NOT EXISTS idx_recuperacion_usuario_activa
    ON recuperaciones_contrasena (usu_id, rec_act, rec_fec_cre DESC);
