ALTER TABLE productos ADD COLUMN IF NOT EXISTS pro_nov BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE productos ADD COLUMN IF NOT EXISTS pro_mej_pre BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE productos ADD COLUMN IF NOT EXISTS pro_out BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE servicios ADD COLUMN IF NOT EXISTS ser_nov BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE servicios ADD COLUMN IF NOT EXISTS ser_mej_pre BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE servicios ADD COLUMN IF NOT EXISTS ser_out BOOLEAN NOT NULL DEFAULT FALSE;
