-- Restaura la generación automática del identificador de mallas.
-- La entidad JPA utiliza GenerationType.IDENTITY y PostgreSQL debe generar mal_id.
ALTER TABLE mallas
    ALTER COLUMN mal_id ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT setval(
    pg_get_serial_sequence('public.mallas', 'mal_id'),
    COALESCE((SELECT MAX(mal_id) FROM mallas), 1),
    EXISTS (SELECT 1 FROM mallas)
);
