package com.jbrempresa.backend.controller;
import java.math.BigDecimal;import java.util.*;import org.springframework.http.*;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.bind.annotation.*;import org.springframework.web.server.ResponseStatusException;
import com.jbrempresa.backend.core.context.ContextoOperacion;import com.jbrempresa.backend.entity.*;import com.jbrempresa.backend.repository.*;
@RestController @RequestMapping("/caja") public class CajaController{
 private final CajaRepository cajas;private final CajaSesionRepository sesiones;private final CajaMovimientoRepository movimientos;private final PersonaRepository personas;private final DocumentoVentaRepository documentos;private final ContextoOperacion contexto;
 public CajaController(CajaRepository c,CajaSesionRepository s,CajaMovimientoRepository m,PersonaRepository p,DocumentoVentaRepository d,ContextoOperacion x){cajas=c;sesiones=s;movimientos=m;personas=p;documentos=d;contexto=x;}
 @GetMapping("/cajas")public List<Caja> cajas(){return cajas.findByEmpIdOrderByCajNom(emp());}
 @PostMapping("/cajas")public Caja crearCaja(@RequestBody Caja c){c.setCajId(null);preparar(c);validarCaja(c);return cajas.save(c);}
 @PutMapping("/cajas/{id}")public Caja editarCaja(@PathVariable Long id,@RequestBody Caja c){caja(id);c.setCajId(id);preparar(c);validarCaja(c);return cajas.save(c);}
 @DeleteMapping("/cajas/{id}")public void eliminarCaja(@PathVariable Long id){Caja c=caja(id);if(sesiones.existsByEmpIdAndCajId(emp(),id))throw conflicto("La caja tiene sesiones y no se puede eliminar.");cajas.delete(c);}
 @PatchMapping("/cajas/{id}/estado")public Caja estadoCaja(@PathVariable Long id,@RequestBody Estado e){Caja c=caja(id);if(Boolean.FALSE.equals(e.activa())&&sesiones.findByEmpIdAndCajIdAndCasEst(emp(),id,"ABIERTA").isPresent())throw conflicto("Cierre la sesión abierta antes de dar de baja la caja.");c.setCajAct(Boolean.TRUE.equals(e.activa()));c.setCajUsuMov(contexto.nombreUsuario());c.setCajFecMov(contexto.fechaActual());return cajas.save(c);}
 @GetMapping("/sesiones")public List<CajaSesion> sesiones(){return sesiones.findByEmpIdOrderByCasFecApeDesc(emp());}
 @PostMapping("/cajas/{id}/abrir")@Transactional public CajaSesion abrir(@PathVariable Long id,@RequestBody Apertura a){Caja c=caja(id);if(!Boolean.TRUE.equals(c.getCajAct()))throw conflicto("La caja no está activa.");if(sesiones.findByEmpIdAndCajIdAndCasEst(emp(),id,"ABIERTA").isPresent())throw conflicto("La caja ya tiene una sesión abierta.");if(a.importeInicial()==null||a.importeInicial().signum()<0)throw error("El importe inicial no puede ser negativo.");CajaSesion s=new CajaSesion();s.setEmpId(emp());s.setCajId(id);s.setCasEst("ABIERTA");s.setCasFecApe(contexto.fechaActual());s.setCasImpIni(a.importeInicial());s.setCasObs(texto(a.observaciones()));auditar(s);return sesiones.save(s);}
 @PostMapping("/sesiones/{id}/cerrar")@Transactional public CajaSesion cerrar(@PathVariable Long id,@RequestBody Cierre c){CajaSesion s=sesion(id);if(!"ABIERTA".equals(s.getCasEst()))throw conflicto("La sesión ya está cerrada.");if(c.importeContado()==null||c.importeContado().signum()<0)throw error("Debe informar un importe contado válido.");BigDecimal esperado=s.getCasImpIni().add(movimientos.saldoEfectivo(emp(),id));s.setCasEst("CERRADA");s.setCasFecCie(contexto.fechaActual());s.setCasImpEsp(esperado);s.setCasImpCon(c.importeContado());s.setCasImpDif(c.importeContado().subtract(esperado));s.setCasObs(texto(c.observaciones()));auditar(s);return sesiones.save(s);}
 @GetMapping("/sesiones/{id}/movimientos")public List<CajaMovimiento> movimientos(@PathVariable Long id){sesion(id);return movimientos.findByEmpIdAndCasIdAndCamActTrueOrderByCamFecMovDesc(emp(),id);}
 @PostMapping("/sesiones/{id}/movimientos")public CajaMovimiento movimiento(@PathVariable Long id,@RequestBody CajaMovimiento m){CajaSesion s=sesion(id);if(!"ABIERTA".equals(s.getCasEst()))throw conflicto("No se pueden registrar movimientos en una sesión cerrada.");m.setCamId(null);m.setEmpId(emp());m.setCasId(id);m.setCamTip(texto(m.getCamTip()).toUpperCase());m.setCamMed(texto(m.getCamMed()).toUpperCase());m.setCamCon(texto(m.getCamCon()));if(!Set.of("ENTRADA","SALIDA","COBRO","DEVOLUCION").contains(m.getCamTip()))throw error("Tipo de movimiento no permitido.");if(!Set.of("EFECTIVO","TARJETA","TRANSFERENCIA","OTRO").contains(m.getCamMed()))throw error("Medio de pago no permitido.");if(m.getCamImp()==null||m.getCamImp().signum()<=0||m.getCamCon().isBlank())throw error("Concepto e importe positivo son obligatorios.");if(m.getPerId()!=null)personas.findByEmpIdAndPerIdAndPerActTrue(emp(),m.getPerId()).orElseThrow(()->error("Persona no válida."));if(m.getDovId()!=null&&documentos.findByEmpIdAndDovId(emp(),m.getDovId()).isEmpty())throw error("Documento de venta no válido.");m.setCamAct(true);m.setCamUsuMov(contexto.nombreUsuario());m.setCamFecMov(contexto.fechaActual());return movimientos.save(m);}
 @DeleteMapping("/movimientos/{id}")public void anular(@PathVariable Long id){CajaMovimiento m=movimientos.findById(id).filter(x->x.getEmpId().equals(emp())).orElseThrow(()->noEncontrado("Movimiento no encontrado."));if(!"ABIERTA".equals(sesion(m.getCasId()).getCasEst()))throw conflicto("No se puede anular un movimiento de una sesión cerrada.");m.setCamAct(false);m.setCamUsuMov(contexto.nombreUsuario());m.setCamFecMov(contexto.fechaActual());movimientos.save(m);}
 private void preparar(Caja c){c.setEmpId(emp());c.setCajNom(texto(c.getCajNom()));c.setCajDes(texto(c.getCajDes()));if(c.getCajAct()==null)c.setCajAct(true);c.setCajUsuMov(contexto.nombreUsuario());c.setCajFecMov(contexto.fechaActual());}
 private void validarCaja(Caja c){if(c.getCajNom().isBlank())throw error("El nombre es obligatorio.");if(cajas.existsByEmpIdAndCajNomIgnoreCaseAndCajIdNot(emp(),c.getCajNom(),c.getCajId()==null?-1L:c.getCajId()))throw conflicto("Ya existe una caja con ese nombre.");}
 private Caja caja(Long id){return cajas.findByEmpIdAndCajId(emp(),id).orElseThrow(()->noEncontrado("Caja no encontrada."));}private CajaSesion sesion(Long id){return sesiones.findByEmpIdAndCasId(emp(),id).orElseThrow(()->noEncontrado("Sesión no encontrada."));}private void auditar(CajaSesion s){s.setCasUsuMov(contexto.nombreUsuario());s.setCasFecMov(contexto.fechaActual());}private Long emp(){return contexto.empresaId();}private String texto(String s){return s==null?"":s.trim();}private ResponseStatusException error(String s){return new ResponseStatusException(HttpStatus.BAD_REQUEST,s);}private ResponseStatusException conflicto(String s){return new ResponseStatusException(HttpStatus.CONFLICT,s);}private ResponseStatusException noEncontrado(String s){return new ResponseStatusException(HttpStatus.NOT_FOUND,s);}
 public record Apertura(BigDecimal importeInicial,String observaciones){}public record Cierre(BigDecimal importeContado,String observaciones){}public record Estado(Boolean activa){}
}
