package com.jbrempresa.backend.controller;
import java.time.LocalDateTime; import java.util.*; import org.springframework.web.bind.annotation.*;
import com.jbrempresa.backend.core.context.ContextoOperacion; import com.jbrempresa.backend.entity.*; import com.jbrempresa.backend.repository.*;

@RestController @RequestMapping("/territorio")
public class CatalogoTerritorialController {
 private static final Set<String> TIPOS_VIA=Set.of("Calle","Avenida","Plaza","Paseo","Camino","Carretera","Travesía","Urbanización","Polígono","Otro");
 private final PaisRepository paises; private final ProvinciaRepository provincias; private final MunicipioRepository municipios; private final CodigoPostalRepository codigos; private final ViaRepository vias; private final DomicilioRepository domicilios; private final ContextoOperacion contexto;
 public CatalogoTerritorialController(PaisRepository a,ProvinciaRepository b,MunicipioRepository c,CodigoPostalRepository d,ViaRepository e,DomicilioRepository f,ContextoOperacion g){paises=a;provincias=b;municipios=c;codigos=d;vias=e;domicilios=f;contexto=g;}

 @GetMapping("/paises") public List<Pais> paises(){return paises.findByEmpIdOrderByPaiNom(cli());}
 @PostMapping("/paises") public Pais crearPais(@RequestBody Pais v){v.setPaiId(null);prep(v);valPais(v,null);return paises.save(v);}
 @PutMapping("/paises/{id}") public Pais editarPais(@PathVariable Long id,@RequestBody Pais v){paises.findByEmpIdAndPaiId(cli(),id).orElseThrow(()->error("País no encontrado."));v.setPaiId(id);prep(v);valPais(v,id);return paises.save(v);}
 @DeleteMapping("/paises/{id}") public void borrarPais(@PathVariable Long id){Pais v=paises.findByEmpIdAndPaiId(cli(),id).orElseThrow(()->error("País no encontrado."));if(provincias.existsByEmpIdAndPaiId(cli(),id))throw error("No se puede eliminar: tiene provincias relacionadas.");paises.delete(v);}

 @GetMapping("/provincias") public List<Provincia> provincias(){return provincias.findByEmpIdOrderByPrvNom(cli());}
 @PostMapping("/provincias") public Provincia crearProvincia(@RequestBody Provincia v){v.setPrvId(null);prep(v);valProvincia(v,null);return provincias.save(v);}
 @PutMapping("/provincias/{id}") public Provincia editarProvincia(@PathVariable Long id,@RequestBody Provincia v){provincias.findByEmpIdAndPrvId(cli(),id).orElseThrow(()->error("Provincia no encontrada."));v.setPrvId(id);prep(v);valProvincia(v,id);return provincias.save(v);}
 @DeleteMapping("/provincias/{id}") public void borrarProvincia(@PathVariable Long id){Provincia v=provincias.findByEmpIdAndPrvId(cli(),id).orElseThrow(()->error("Provincia no encontrada."));if(municipios.existsByEmpIdAndPrvId(cli(),id))throw error("No se puede eliminar: tiene municipios relacionados.");provincias.delete(v);}

 @GetMapping("/municipios") public List<Municipio> municipios(){return municipios.findByEmpIdOrderByMunNom(cli());}
 @PostMapping("/municipios") public Municipio crearMunicipio(@RequestBody Municipio v){v.setMunId(null);prep(v);valMunicipio(v,null);return municipios.save(v);}
 @PutMapping("/municipios/{id}") public Municipio editarMunicipio(@PathVariable Long id,@RequestBody Municipio v){municipios.findByEmpIdAndMunId(cli(),id).orElseThrow(()->error("Municipio no encontrado."));v.setMunId(id);prep(v);valMunicipio(v,id);return municipios.save(v);}
 @DeleteMapping("/municipios/{id}") public void borrarMunicipio(@PathVariable Long id){Municipio v=municipios.findByEmpIdAndMunId(cli(),id).orElseThrow(()->error("Municipio no encontrado."));if(codigos.existsByEmpIdAndMunId(cli(),id))throw error("No se puede eliminar: tiene códigos postales relacionados.");municipios.delete(v);}

 @GetMapping("/codigos-postales") public List<CodigoPostal> codigos(){return codigos.findByEmpIdOrderByCopCod(cli());}
 @PostMapping("/codigos-postales") public CodigoPostal crearCodigo(@RequestBody CodigoPostal v){v.setCopId(null);prep(v);valCodigo(v,null);return codigos.save(v);}
 @PutMapping("/codigos-postales/{id}") public CodigoPostal editarCodigo(@PathVariable Long id,@RequestBody CodigoPostal v){codigos.findByEmpIdAndCopId(cli(),id).orElseThrow(()->error("Código postal no encontrado."));v.setCopId(id);prep(v);valCodigo(v,id);return codigos.save(v);}
 @DeleteMapping("/codigos-postales/{id}") public void borrarCodigo(@PathVariable Long id){CodigoPostal v=codigos.findByEmpIdAndCopId(cli(),id).orElseThrow(()->error("Código postal no encontrado."));if(vias.existsByEmpIdAndCopId(cli(),id))throw error("No se puede eliminar: tiene vías relacionadas.");codigos.delete(v);}

 @GetMapping("/vias") public List<Via> vias(){return vias.findByEmpIdOrderByViaNom(cli());}
 @PostMapping("/vias") public Via crearVia(@RequestBody Via v){v.setViaId(null);prep(v);valVia(v,null);return vias.save(v);}
 @PutMapping("/vias/{id}") public Via editarVia(@PathVariable Long id,@RequestBody Via v){vias.findByEmpIdAndViaId(cli(),id).orElseThrow(()->error("Vía no encontrada."));v.setViaId(id);prep(v);valVia(v,id);return vias.save(v);}
 @DeleteMapping("/vias/{id}") public void borrarVia(@PathVariable Long id){Via v=vias.findByEmpIdAndViaId(cli(),id).orElseThrow(()->error("Vía no encontrada."));if(domicilios.existsByEmpIdAndDomViaId(cli(),id))throw error("No se puede eliminar: la vía está utilizada por domicilios.");vias.delete(v);}

 private Long cli(){return contexto.empresaId();} private IllegalArgumentException error(String m){return new IllegalArgumentException(m);} private boolean vacio(String s){return s==null||s.isBlank();} private LocalDateTime fecha(){return contexto.fechaActual();}
 private void prep(Pais v){v.setEmpId(cli());v.setPaiUsuMov(contexto.nombreUsuario());v.setPaiFecMov(fecha());if(v.getPaiAct()==null)v.setPaiAct(true);} private void prep(Provincia v){v.setEmpId(cli());v.setPrvUsuMov(contexto.nombreUsuario());v.setPrvFecMov(fecha());if(v.getPrvAct()==null)v.setPrvAct(true);} private void prep(Municipio v){v.setEmpId(cli());v.setMunUsuMov(contexto.nombreUsuario());v.setMunFecMov(fecha());if(v.getMunAct()==null)v.setMunAct(true);} private void prep(CodigoPostal v){v.setEmpId(cli());v.setCopUsuMov(contexto.nombreUsuario());v.setCopFecMov(fecha());if(v.getCopAct()==null)v.setCopAct(true);} private void prep(Via v){v.setEmpId(cli());v.setViaUsuMov(contexto.nombreUsuario());v.setViaFecMov(fecha());if(v.getViaAct()==null)v.setViaAct(true);}
 private void valPais(Pais v,Long id){if(vacio(v.getPaiCod())||vacio(v.getPaiNom()))throw error("Código y nombre son obligatorios.");if(id==null?paises.existsByEmpIdAndPaiCodIgnoreCase(cli(),v.getPaiCod()):paises.existsByEmpIdAndPaiCodIgnoreCaseAndPaiIdNot(cli(),v.getPaiCod(),id))throw error("Ya existe ese código de país.");}
 private void valProvincia(Provincia v,Long id){if(vacio(v.getPrvCod())||vacio(v.getPrvNom())||v.getPaiId()==null)throw error("País, código y nombre son obligatorios.");paises.findByEmpIdAndPaiId(cli(),v.getPaiId()).filter(x->Boolean.TRUE.equals(x.getPaiAct())).orElseThrow(()->error("El país no es válido."));if(id==null?provincias.existsByEmpIdAndPrvCodIgnoreCase(cli(),v.getPrvCod()):provincias.existsByEmpIdAndPrvCodIgnoreCaseAndPrvIdNot(cli(),v.getPrvCod(),id))throw error("Ya existe ese código de provincia.");}
 private void valMunicipio(Municipio v,Long id){if(vacio(v.getMunCod())||vacio(v.getMunNom())||v.getPrvId()==null)throw error("Provincia, código y nombre son obligatorios.");provincias.findByEmpIdAndPrvId(cli(),v.getPrvId()).filter(x->Boolean.TRUE.equals(x.getPrvAct())).orElseThrow(()->error("La provincia no es válida."));if(id==null?municipios.existsByEmpIdAndMunCodIgnoreCase(cli(),v.getMunCod()):municipios.existsByEmpIdAndMunCodIgnoreCaseAndMunIdNot(cli(),v.getMunCod(),id))throw error("Ya existe ese código de municipio.");}
 private void valCodigo(CodigoPostal v,Long id){if(vacio(v.getCopCod())||v.getMunId()==null)throw error("Municipio y código postal son obligatorios.");municipios.findByEmpIdAndMunId(cli(),v.getMunId()).filter(x->Boolean.TRUE.equals(x.getMunAct())).orElseThrow(()->error("El municipio no es válido."));if(id==null?codigos.existsByEmpIdAndCopCodIgnoreCase(cli(),v.getCopCod()):codigos.existsByEmpIdAndCopCodIgnoreCaseAndCopIdNot(cli(),v.getCopCod(),id))throw error("Ya existe ese código postal.");}
 private void valVia(Via v,Long id){if(vacio(v.getViaCod())||vacio(v.getViaNom())||vacio(v.getViaTip())||v.getCopId()==null)throw error("Tipo, código, nombre y código postal son obligatorios.");if(!TIPOS_VIA.contains(v.getViaTip()))throw error("El tipo de vía no está permitido.");codigos.findByEmpIdAndCopId(cli(),v.getCopId()).filter(x->Boolean.TRUE.equals(x.getCopAct())).orElseThrow(()->error("El código postal no es válido."));if(id==null?vias.existsByEmpIdAndViaCodIgnoreCase(cli(),v.getViaCod()):vias.existsByEmpIdAndViaCodIgnoreCaseAndViaIdNot(cli(),v.getViaCod(),id))throw error("Ya existe ese código de vía.");}
}
