package com.jbrempresa.backend.controller;
import java.math.BigDecimal;import java.util.*;import org.springframework.web.bind.annotation.*;import com.jbrempresa.backend.core.context.ContextoOperacion;import com.jbrempresa.backend.entity.Componente;import com.jbrempresa.backend.service.ComponenteService;
@RestController @RequestMapping("/componentes") public class ComponenteController{private final ComponenteService servicio;private final ContextoOperacion ctx;public ComponenteController(ComponenteService s,ContextoOperacion c){servicio=s;ctx=c;}
 @GetMapping public List<Componente> listar(){return servicio.listar(ctx.empresaConsulta(null));}@GetMapping("/{id}/historico")public List<Componente> historico(@PathVariable Long id){return servicio.historico(ctx.empresaId(),id);}
 @PostMapping public Componente guardar(@RequestBody Componente i){validar(i);return servicio.guardar(ctx.empresaId(),ctx.nombreUsuario(),i);}@PutMapping("/{id}")public Componente actualizar(@PathVariable Long id,@RequestBody Componente i){validar(i);return servicio.actualizar(ctx.empresaId(),ctx.nombreUsuario(),id,i);}
 @DeleteMapping("/{id}")public void eliminar(@PathVariable Long id){servicio.eliminar(ctx.empresaId(),id);}@PostMapping("/{id}/baja")public Componente baja(@PathVariable Long id){return servicio.baja(ctx.empresaId(),ctx.nombreUsuario(),id);}
 @PostMapping("/{id}/deshacer")public Componente deshacer(@PathVariable Long id){return servicio.deshacer(ctx.empresaId(),id);}
 private void validar(Componente i){Set<String> tipos=Set.of("INGREDIENTE","MATERIA_PRIMA","PIEZA","MATERIAL","ENVASE","ACCESORIO");if(i.getCmpTip()==null||!tipos.contains(i.getCmpTip()))throw new IllegalArgumentException("El tipo de componente no es válido.");if(i.getCmpNom()==null||i.getCmpNom().isBlank())throw new IllegalArgumentException("El nombre del componente es obligatorio.");if(i.getCmpPreAdi()==null)i.setCmpPreAdi(BigDecimal.ZERO);if(i.getCmpIva()==null)i.setCmpIva(BigDecimal.ZERO);if(i.getCmpPreAdi().signum()<0||i.getCmpIva().signum()<0||i.getCmpIva().compareTo(new BigDecimal("100"))>0)throw new IllegalArgumentException("Revise el precio adicional y el IVA del componente.");}
}
