package com.jbrempresa.backend.controller;
import java.util.List;import org.springframework.transaction.annotation.Transactional;import com.jbrempresa.backend.service.CompraLineasService;import org.springframework.web.bind.annotation.*;import com.jbrempresa.backend.core.context.ContextoOperacion;import com.jbrempresa.backend.dto.compras.CompraDtos;import com.jbrempresa.backend.entity.Compra;import com.jbrempresa.backend.exception.RecursoNoEncontradoException;import com.jbrempresa.backend.repository.CompraRepository;import jakarta.validation.Valid;
@RestController @RequestMapping("/compras")
public class CompraController{
 private final CompraLineasService lineas;private final CompraRepository compras;private final ContextoOperacion contexto;
 public CompraController(CompraRepository compras,ContextoOperacion contexto,CompraLineasService lineas){this.lineas=lineas;this.compras=compras;this.contexto=contexto;}
 @PostMapping @Transactional public CompraDtos.Salida guardar(@Valid @RequestBody CompraDtos.Entrada entrada){Compra v=entrada.entidad();v.setEmpId(contexto.empresaId());v.setComUsuMov(contexto.nombreUsuario());v.setComFecMov(contexto.fechaActual());v.setComAct(true);lineas.preparar(v);Compra guardada=compras.save(v);guardada.setDetalles(v.getDetalles());return CompraDtos.Salida.desde(lineas.guardar(guardada));}
 @PutMapping("/{id}") @Transactional public CompraDtos.Salida actualizar(@PathVariable Long id,@Valid @RequestBody CompraDtos.Entrada entrada){Compra actual=obtener(id);validarIndependiente(actual);Compra v=entrada.entidad();v.setComId(actual.getComId());v.setEmpId(contexto.empresaId());v.setComUsuMov(contexto.nombreUsuario());v.setComFecMov(contexto.fechaActual());v.setComAct(actual.getComAct());lineas.preparar(v);Compra guardada=compras.save(v);guardada.setDetalles(v.getDetalles());return CompraDtos.Salida.desde(lineas.guardar(guardada));}
 @GetMapping public List<CompraDtos.Salida> consultar(){Long empresa=contexto.empresaConsulta(null);return (empresa==null?compras.findAllByOrderByEmpIdAscComIdAsc():compras.findByEmpId(empresa)).stream().map(lineas::cargar).map(compra->CompraDtos.Salida.desde(compra)).toList();}
 @GetMapping("/siguiente-id") public Long siguienteId(){return compras.obtenerSiguienteId(contexto.empresaId());}
 @DeleteMapping("/{id}") @Transactional public void eliminar(@PathVariable Long id){Compra compra=obtener(id);validarIndependiente(compra);lineas.eliminar(compra);compras.delete(compra);}
 private void validarIndependiente(Compra compra){if(compra.getPedidoVentaId()!=null)throw new IllegalArgumentException("La compra está vinculada a un pedido del proveedor y no admite cambios independientes.");}
 private Compra obtener(Long id){return compras.findByEmpIdAndComId(contexto.empresaId(),id).orElseThrow(()->new RecursoNoEncontradoException("Compra no encontrada."));}
}
