package com.jbrempresa.backend.controller;

import java.util.*; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.bind.annotation.*;
import com.jbrempresa.backend.core.context.ContextoOperacion; import com.jbrempresa.backend.core.comunicaciones.RecepcionMensajeService; import com.jbrempresa.backend.core.comunicaciones.EnvioWhatsappService; import com.jbrempresa.backend.dto.comunicaciones.ComunicacionDtos.*; import com.jbrempresa.backend.entity.*; import com.jbrempresa.backend.repository.*; import jakarta.validation.Valid;

@RestController @RequestMapping("/comunicaciones")
@SuppressWarnings("unused")
public class ComunicacionController {
 private static final Set<String> TIPOS=Set.of("CONVERSACION","AVISO","ALERTA"); private static final Set<String> ORIGENES=Set.of("ENTRADA","SALIDA","INTERNA"); private static final Set<String> CANALES=Set.of("SIMULADO","EMAIL","WHATSAPP","INTERNO"); private static final Set<String> ESTADOS=Set.of("NUEVA","EN_PROCESO","PENDIENTE_CLIENTE","PENDIENTE_USUARIO","RESUELTA","CERRADA","ERROR"); private static final Set<String> AUTORES=Set.of("CLIENTE","USUARIO","IA","SISTEMA"); private static final Set<String> INTENCIONES=Set.of("CONSULTA_PRODUCTO","SOLICITUD_PRESUPUESTO","PEDIDO","CITA_RESERVA","INCIDENCIA","INFORMACION_GENERAL","OTRO");
 private final ComunicacionRepository comunicaciones; private final MensajeRepository mensajes; private final ContactoCanalRepository contactos; private final PersonaContactoCanalRepository personasContacto; private final PersonaRepository personas; private final UsuarioRepository usuarios; private final AreaOrganizativaRepository areas; private final ContextoOperacion contexto; private final RecepcionMensajeService recepcion; private final EnvioWhatsappService envioWhatsapp;
 public ComunicacionController(ComunicacionRepository a,MensajeRepository b,ContactoCanalRepository c,PersonaContactoCanalRepository d,PersonaRepository e,UsuarioRepository f,AreaOrganizativaRepository g,ContextoOperacion h,RecepcionMensajeService i,EnvioWhatsappService j){comunicaciones=a;mensajes=b;contactos=c;personasContacto=d;personas=e;usuarios=f;areas=g;contexto=h;recepcion=i;envioWhatsapp=j;}

 @GetMapping public List<ConversacionSalida> consultar(){return comunicaciones.findByEmpIdAndComActTrueOrderByComFecUltDesc(cli()).stream().map(conversacion->ConversacionSalida.desde(conversacion)).toList();}
 @GetMapping("/entrada") public List<MensajeSalida> entrada(){return mensajes.findByEmpIdAndComIdIsNullAndMenActTrueOrderByMenFecRecDesc(cli()).stream().map(mensaje->MensajeSalida.desde(mensaje)).toList();}
 @GetMapping("/entrada/{mensajeId}/candidatos") public List<Persona> candidatos(@PathVariable Long mensajeId){Mensaje m=mensajeEntrada(mensajeId);if(m.getCocId()!=null){List<Persona> vinculadas=personasContacto.findByEmpIdAndCocIdAndPccActTrue(cli(),m.getCocId()).stream().map(r->personas.findByEmpIdAndPerIdAndPerActTrue(cli(),r.getPerId()).orElse(null)).filter(persona->persona!=null).toList();if(!vinculadas.isEmpty())return vinculadas;}return personas.buscarCoincidenciasExactas(cli(),texto(m.getMenDniRem()),texto(m.getMenTelRem()),texto(m.getMenEmaRem()));}
 @PatchMapping("/entrada/{mensajeId}/persona/{personaId}") @Transactional public MensajeSalida confirmarPersona(@PathVariable Long mensajeId,@PathVariable Long personaId){Mensaje m=mensajeEntrada(mensajeId);persona(personaId);m.setPerId(personaId);m.setMenConPer(1D);m.setMenUsuMov(contexto.nombreUsuario());m.setMenFecMov(contexto.fechaActual());if(m.getCocId()!=null)guardarRelacion(m.getCocId(),personaId);return MensajeSalida.desde(mensajes.save(m));}
 @PostMapping("/entrada") @Transactional public MensajeSalida recibir(@Valid @RequestBody MensajeEntrada datos){return MensajeSalida.desde(recepcion.recibir(cli(),datos.entidad(),contexto.nombreUsuario()));}
 @PatchMapping("/entrada/{mensajeId}/clasificacion") @Transactional public MensajeSalida confirmarClasificacion(@PathVariable Long mensajeId,@Valid @RequestBody ClasificacionEntrada datos){Mensaje m=mensajeEntrada(mensajeId);String intencion=texto(datos.menInt()).toUpperCase();if(!INTENCIONES.contains(intencion))throw error("Intención de mensaje no permitida.");m.setMenInt(intencion);m.setMenEstCla("CONFIRMADA");m.setMenOriCla("USUARIO");m.setMenConInt(1D);m.setMenEst("PENDIENTE_VINCULAR");m.setMenUsuMov(contexto.nombreUsuario());m.setMenFecMov(contexto.fechaActual());return MensajeSalida.desde(mensajes.save(m));}
 @PostMapping("/entrada/{mensajeId}/nueva-conversacion") @Transactional public ConversacionSalida nuevaConversacion(@PathVariable Long mensajeId,@Valid @RequestBody ConversacionEntrada datos){Mensaje m=mensajeEntrada(mensajeId);if(m.getPerId()==null)throw error("Debe confirmar la Persona antes de crear una conversación.");if(!"CONFIRMADA".equals(m.getMenEstCla()))throw error("Debe confirmar la clasificación del mensaje.");Comunicacion v=datos.entidad();v.setComId(null);v.setPerId(m.getPerId());v.setComInt(m.getMenInt());v.setComOri("ENTRADA");v.setComCan(m.getMenCan());preparar(v);validar(v);Comunicacion c=comunicaciones.save(v);vincular(m,c);return ConversacionSalida.desde(c);}
 @PostMapping("/entrada/{mensajeId}/vincular/{comunicacionId}") @Transactional public Mensaje vincularExistente(@PathVariable Long mensajeId,@PathVariable Long comunicacionId){Mensaje m=mensajeEntrada(mensajeId);if(m.getPerId()==null)throw error("Debe confirmar la Persona antes de vincular el mensaje.");Comunicacion c=comunicacion(comunicacionId);if(c.getPerId()==null||!m.getPerId().equals(c.getPerId()))throw error("El mensaje y la conversación deben pertenecer a la misma Persona.");vincular(m,c);return m;}
 @GetMapping("/{id}") public ConversacionSalida obtener(@PathVariable Long id){return ConversacionSalida.desde(comunicacion(id));}
 @GetMapping("/persona/{personaId}") public List<ConversacionSalida> conversacionesPersona(@PathVariable Long personaId){persona(personaId);return comunicaciones.findByEmpIdAndPerIdAndComActTrueOrderByComFecUltDesc(cli(),personaId).stream().map(conversacion->ConversacionSalida.desde(conversacion)).toList();}
 @PostMapping @Transactional public ConversacionSalida crear(@Valid @RequestBody ConversacionEntrada datos){Comunicacion v=datos.entidad();v.setComId(null);preparar(v);validar(v);return ConversacionSalida.desde(comunicaciones.save(v));}
 @PutMapping("/{id}") @Transactional public ConversacionSalida actualizar(@PathVariable Long id,@Valid @RequestBody ConversacionEntrada datos){comunicacion(id);Comunicacion v=datos.entidad();v.setComId(id);preparar(v);validar(v);return ConversacionSalida.desde(comunicaciones.save(v));}
 @PatchMapping("/{id}/estado/{estado}") @Transactional public ConversacionSalida estado(@PathVariable Long id,@PathVariable String estado){Comunicacion v=comunicacion(id);String e=estado.toUpperCase();if(!ESTADOS.contains(e))throw error("Estado de comunicación no permitido.");v.setComEst(e);v.setComUsuMov(contexto.nombreUsuario());v.setComFecMov(contexto.fechaActual());return ConversacionSalida.desde(comunicaciones.save(v));}
 @PatchMapping("/{id}/asignacion") @Transactional public ConversacionSalida asignar(@PathVariable Long id,@RequestParam(required=false) Long usuId,@RequestParam(required=false) Long areId){Comunicacion v=comunicacion(id);if(usuId!=null)usuarios.findByEmpIdAndUsuId(cli(),usuId).orElseThrow(()->error("Usuario asignado no válido."));if(areId!=null)areas.findByEmpIdAndAreId(cli(),areId).orElseThrow(()->error("Área asignada no válida."));v.setUsuId(usuId);v.setAreId(areId);v.setComUsuMov(contexto.nombreUsuario());v.setComFecMov(contexto.fechaActual());return ConversacionSalida.desde(comunicaciones.save(v));}
 @GetMapping("/{id}/mensajes") public List<MensajeSalida> mensajes(@PathVariable Long id){comunicacion(id);return mensajes.findByEmpIdAndComIdAndMenActTrueOrderByMenSec(cli(),id).stream().map(mensaje->MensajeSalida.desde(mensaje)).toList();}
 @PostMapping("/{id}/mensajes") @Transactional public MensajeSalida mensaje(@PathVariable Long id,@Valid @RequestBody RespuestaEntrada datos){Comunicacion c=comunicacion(id);Mensaje v=datos.entidad();v.setMenId(null);v.setEmpId(cli());v.setComId(id);v.setMenSec(mensajes.siguienteSecuencia(cli(),id));if(v.getMenDir()==null)v.setMenDir("INTERNA");v.setMenDir(v.getMenDir().toUpperCase());if(v.getMenAut()==null)v.setMenAut("USUARIO");v.setMenAut(v.getMenAut().toUpperCase());if(!ORIGENES.contains(v.getMenDir()))throw error("Dirección del mensaje no permitida.");if(!AUTORES.contains(v.getMenAut()))throw error("Autor del mensaje no permitido.");if(v.getMenIdExt()!=null&&!v.getMenIdExt().isBlank()&&mensajes.existsByEmpIdAndMenIdExt(cli(),v.getMenIdExt()))throw error("El mensaje externo ya fue procesado.");v.setMenCan(c.getComCan());if("WHATSAPP".equals(c.getComCan())&&"SALIDA".equals(v.getMenDir())){Mensaje entrada=mensajes.findTopByEmpIdAndComIdAndMenDirAndMenActTrueOrderByMenSecDesc(cli(),id,"ENTRADA").orElseThrow(()->error("La conversación no contiene un mensaje de WhatsApp de entrada."));String destino=texto(entrada.getMenTelRem()).isBlank()?entrada.getMenRem():entrada.getMenTelRem();EnvioWhatsappService.Resultado resultado=envioWhatsapp.enviarTexto(cli(),destino,v.getMenCon());v.setMenIdExt(resultado.idExterno());v.setMenDes(resultado.destinatario());v.setMenEst("ENVIADO");}else v.setMenEst(v.getMenEst()==null?"REGISTRADO":v.getMenEst());v.setMenUsuMov(contexto.nombreUsuario());v.setMenFecMov(contexto.fechaActual());v.setMenAct(true);Mensaje guardado=mensajes.save(v);c.setComFecUlt(v.getMenFecMov());c.setComUsuMov(contexto.nombreUsuario());c.setComFecMov(contexto.fechaActual());if("NUEVA".equals(c.getComEst()))c.setComEst("EN_PROCESO");comunicaciones.save(c);return MensajeSalida.desde(guardado);}
 @GetMapping("/contactos") public List<ContactoSalida> contactos(){return contactos.findByEmpIdAndCocActTrueOrderByCocIde(cli()).stream().map(contacto->ContactoSalida.desde(contacto)).toList();}
 @GetMapping("/contactos/sin-identificar") public List<ContactoSalida> contactosSinIdentificar(){return contactos.sinIdentificar(cli()).stream().map(contacto->ContactoSalida.desde(contacto)).toList();}
 @GetMapping("/contactos/{contactoId}/personas") public List<PersonaContactoCanal> personasContacto(@PathVariable Long contactoId){contactos.findByEmpIdAndCocId(cli(),contactoId).orElseThrow(()->error("Contacto de canal no encontrado."));return personasContacto.findByEmpIdAndCocIdAndPccActTrue(cli(),contactoId);}
 @PostMapping("/contactos/{contactoId}/persona/{personaId}") @Transactional public PersonaContactoCanal identificarContacto(@PathVariable Long contactoId,@PathVariable Long personaId){contactos.findByEmpIdAndCocId(cli(),contactoId).orElseThrow(()->error("Contacto de canal no encontrado."));persona(personaId);if(personasContacto.existsByEmpIdAndCocIdAndPerIdAndPccActTrue(cli(),contactoId,personaId))throw error("La Persona ya está relacionada con esta identidad.");return guardarRelacion(contactoId,personaId);}
 @DeleteMapping("/contactos/{contactoId}/persona/{personaId}") @Transactional public void revocarContacto(@PathVariable Long contactoId,@PathVariable Long personaId){contactos.findByEmpIdAndCocId(cli(),contactoId).orElseThrow(()->error("Contacto de canal no encontrado."));PersonaContactoCanal r=personasContacto.findByEmpIdAndCocIdAndPerId(cli(),contactoId,personaId).filter(x->Boolean.TRUE.equals(x.getPccAct())).orElseThrow(()->error("La relación activa no existe."));r.setPccAct(false);r.setPccUsuMov(contexto.nombreUsuario());r.setPccFecMov(contexto.fechaActual());personasContacto.save(r);}
 @PostMapping("/contactos") public ContactoSalida contacto(@Valid @RequestBody ContactoEntrada datos){ContactoCanal v=new ContactoCanal();v.setCocCan(datos.cocCan());v.setCocIde(datos.cocIde());v.setCocId(null);v.setEmpId(cli());v.setCocCan(v.getCocCan().toUpperCase());if(!CANALES.contains(v.getCocCan()))throw error("Canal no permitido.");if(contactos.existsByEmpIdAndCocCanAndCocIdeIgnoreCase(cli(),v.getCocCan(),v.getCocIde()))throw error("La identidad del canal ya existe.");v.setCocUsuMov(contexto.nombreUsuario());v.setCocFecMov(contexto.fechaActual());v.setCocAct(true);return ContactoSalida.desde(contactos.save(v));}

 private void preparar(Comunicacion v){v.setEmpId(cli());v.setComTip(v.getComTip()==null?"CONVERSACION":v.getComTip().toUpperCase());v.setComOri(v.getComOri()==null?"INTERNA":v.getComOri().toUpperCase());v.setComCan(v.getComCan()==null?"SIMULADO":v.getComCan().toUpperCase());v.setComEst(v.getComEst()==null?"NUEVA":v.getComEst().toUpperCase());v.setComFecUlt(v.getComFecUlt()==null?contexto.fechaActual():v.getComFecUlt());v.setComUsuMov(contexto.nombreUsuario());v.setComFecMov(contexto.fechaActual());if(v.getComAct()==null)v.setComAct(true);}
 private void validar(Comunicacion v){if(!TIPOS.contains(v.getComTip()))throw error("Tipo de comunicación no permitido.");if(!ORIGENES.contains(v.getComOri())||!CANALES.contains(v.getComCan())||!ESTADOS.contains(v.getComEst()))throw error("Origen, canal o estado no permitido.");if(v.getComAsu()==null||v.getComAsu().isBlank())throw error("El asunto es obligatorio.");if(v.getPerId()!=null)persona(v.getPerId());if(v.getUsuId()!=null)usuarios.findByEmpIdAndUsuId(cli(),v.getUsuId()).orElseThrow(()->error("Usuario asignado no válido."));if(v.getAreId()!=null)areas.findByEmpIdAndAreId(cli(),v.getAreId()).orElseThrow(()->error("Área asignada no válida."));}
 private void persona(Long id){personas.findByEmpIdAndPerIdAndPerActTrue(cli(),id).filter(p->!"B".equals(p.getPerTipMov())).orElseThrow(()->error("Persona no válida."));}
 private Mensaje mensajeEntrada(Long id){return mensajes.findByEmpIdAndMenIdAndMenActTrue(cli(),id).filter(m->m.getComId()==null).orElseThrow(()->error("Mensaje de entrada no encontrado o ya vinculado."));}
 private void vincular(Mensaje m,Comunicacion c){if(!"CONFIRMADA".equals(m.getMenEstCla()))throw error("Debe confirmar la clasificación del mensaje.");m.setComId(c.getComId());m.setMenSec(mensajes.siguienteSecuencia(cli(),c.getComId()));m.setMenEst("VINCULADO");m.setMenFecPro(contexto.fechaActual());m.setMenUsuMov(contexto.nombreUsuario());m.setMenFecMov(contexto.fechaActual());mensajes.save(m);if(c.getComInt()==null||c.getComInt().isBlank())c.setComInt(m.getMenInt());c.setComFecUlt(m.getMenFecRec()==null?contexto.fechaActual():m.getMenFecRec());c.setComUsuMov(contexto.nombreUsuario());c.setComFecMov(contexto.fechaActual());comunicaciones.save(c);}
 private Comunicacion comunicacion(Long id){return comunicaciones.findByEmpIdAndComIdAndComActTrue(cli(),id).orElseThrow(()->error("Comunicación no encontrada."));} private Long cli(){return contexto.empresaId();} private IllegalArgumentException error(String m){return new IllegalArgumentException(m);}
 private String texto(String v){return v==null?"":v.trim();}
 private String identidad(Mensaje v){if(v.getMenRem()!=null&&!v.getMenRem().isBlank())return v.getMenRem().trim();if("EMAIL".equals(v.getMenCan()))return texto(v.getMenEmaRem());if("WHATSAPP".equals(v.getMenCan()))return texto(v.getMenTelRem());if(!texto(v.getMenEmaRem()).isBlank())return texto(v.getMenEmaRem());if(!texto(v.getMenTelRem()).isBlank())return texto(v.getMenTelRem());return texto(v.getMenDniRem());}
 private PersonaContactoCanal guardarRelacion(Long contactoId,Long personaId){PersonaContactoCanal r=personasContacto.findByEmpIdAndCocIdAndPerId(cli(),contactoId,personaId).orElseGet(PersonaContactoCanal::new);r.setEmpId(cli());r.setCocId(contactoId);r.setPerId(personaId);r.setPccTip("CONFIRMADA");r.setPccUsuMov(contexto.nombreUsuario());r.setPccFecMov(contexto.fechaActual());r.setPccAct(true);return personasContacto.save(r);}
 private ContactoCanal nuevoContacto(String canal,String identidad){ContactoCanal c=new ContactoCanal();c.setEmpId(cli());c.setCocCan(canal);c.setCocIde(identidad);c.setCocUsuMov(contexto.nombreUsuario());c.setCocFecMov(contexto.fechaActual());c.setCocAct(true);return contactos.save(c);}
 private void clasificarPorReglas(Mensaje m){String t=(texto(m.getMenAsu())+" "+texto(m.getMenCon())).toLowerCase();String i="OTRO";double confianza=.45;if(contiene(t,"presupuesto","cotizacion","cotización")){i="SOLICITUD_PRESUPUESTO";confianza=.85;}else if(contiene(t,"pedido","comprar","encargo")){i="PEDIDO";confianza=.82;}else if(contiene(t,"cita","reserva","reservar","hora")){i="CITA_RESERVA";confianza=.82;}else if(contiene(t,"averia","avería","problema","reclamacion","reclamación","incidencia")){i="INCIDENCIA";confianza=.80;}else if(contiene(t,"producto","precio","stock","disponible","teneis","tenéis")){i="CONSULTA_PRODUCTO";confianza=.75;}else if(contiene(t,"informacion","información","consulta","horario")){i="INFORMACION_GENERAL";confianza=.68;}m.setMenInt(i);m.setMenConInt(confianza);m.setMenOriCla("REGLAS");m.setMenEstCla("PROPUESTA");}
 private boolean contiene(String texto,String... valores){return Arrays.stream(valores).anyMatch(texto::contains);}
}
