package com.jbrempresa.backend.controller;

import java.util.*; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.bind.annotation.*; import org.springframework.http.HttpStatus; import org.springframework.web.server.ResponseStatusException;
import com.jbrempresa.backend.core.context.ContextoOperacion; import com.jbrempresa.backend.entity.*; import com.jbrempresa.backend.repository.*; import com.jbrempresa.backend.security.AccesoPerfilService;

@RestController @RequestMapping("/modulos-aplicacion")
public class ModuloAplicacionController {
 private final ModuloAplicacionRepository modulos; private final EmpresaModuloRepository empresas; private final EmpresaRepository empresaRepository; private final AdjuntoRepository adjuntos; private final ContextoOperacion contexto; private final AccesoPerfilService accesos;
 public ModuloAplicacionController(ModuloAplicacionRepository m,EmpresaModuloRepository e,EmpresaRepository er,AdjuntoRepository a,ContextoOperacion c,AccesoPerfilService p){modulos=m;empresas=e;empresaRepository=er;adjuntos=a;contexto=c;accesos=p;}
 public record ModuloEntrada(Long id,String codigo,String titulo,String descripcion,String ruta,Integer posicion){}
 public record ModuloPanel(Long id,String codigo,String titulo,String descripcion,String ruta,Integer posicion,Boolean disponible,Long imagenAdjuntoId){}
 public record Configuracion(Long moduloId,Boolean disponible,Integer posicion){}
 @GetMapping public List<ModuloAplicacion> listar(){soloAdministrador();return modulos.findByActivoTrueOrderByPosicionAscIdAsc();}
 @PostMapping public ModuloAplicacion guardar(@RequestBody ModuloEntrada in){soloAdministrador();validar(in);ModuloAplicacion m=new ModuloAplicacion();aplicar(m,in,true);return modulos.save(m);}
 @PutMapping("/{id}") public ModuloAplicacion actualizar(@PathVariable Long id,@RequestBody ModuloEntrada in){soloAdministrador();validar(in);ModuloAplicacion m=modulos.findById(id).orElseThrow();aplicar(m,in,false);return modulos.save(m);}
 @DeleteMapping("/{id}") public void eliminar(@PathVariable Long id){soloAdministrador();ModuloAplicacion m=modulos.findById(id).orElseThrow();m.setActivo(false);m.setUsuario(contexto.nombreUsuario());m.setFecha(contexto.fechaActual());modulos.save(m);}
 @GetMapping("/gestion") public List<ModuloPanel> gestion(@RequestParam Long empresaId){soloAdministrador();comprobarEmpresa(empresaId);sincronizar(empresaId);return construir(empresaId,false);}
 @PutMapping("/gestion") @Transactional public List<ModuloPanel> gestionar(@RequestParam Long empresaId,@RequestBody List<Configuracion> lista){soloAdministrador();comprobarEmpresa(empresaId);sincronizar(empresaId);List<EmpresaModulo> cambios=new ArrayList<>();Set<Long> ids=new HashSet<>();for(Configuracion c:lista){if(c.moduloId()==null||c.posicion()==null||!ids.add(c.moduloId()))throw new IllegalArgumentException("La configuración de módulos no es válida.");EmpresaModulo e=empresas.findByEmpresaIdAndModuloId(empresaId,c.moduloId()).orElseThrow();e.setDisponible(Boolean.TRUE.equals(c.disponible()));e.setPosicion(Math.max(1,c.posicion()));cambios.add(e);}empresas.saveAll(cambios);empresas.flush();return construir(empresaId,false);}
 @GetMapping("/panel") public List<ModuloPanel> panel(){Long empresaId=contexto.empresaId();sincronizar(empresaId);return construir(empresaId,true).stream().filter(m->accesos.permite(contexto.usuarioActual(),m.codigo())).toList();}
 private void sincronizar(Long empresaId){int pos=1;for(ModuloAplicacion m:modulos.findByActivoTrueOrderByPosicionAscIdAsc()){if(empresas.findByEmpresaIdAndModuloId(empresaId,m.getId()).isEmpty()){EmpresaModulo e=new EmpresaModulo();e.setEmpresaId(empresaId);e.setModuloId(m.getId());e.setDisponible(true);e.setPosicion(m.getPosicion()==null?pos:m.getPosicion());empresas.save(e);}pos++;}}
 private List<ModuloPanel> construir(Long empresaId,boolean soloDisponibles){Map<Long,EmpresaModulo> ec=new HashMap<>();empresas.findByEmpresaId(empresaId).forEach(e->ec.put(e.getModuloId(),e));List<ModuloPanel> salida=new ArrayList<>();for(ModuloAplicacion m:modulos.findByActivoTrueOrderByPosicionAscIdAsc()){EmpresaModulo e=ec.get(m.getId());if(e==null||(soloDisponibles&&!e.getDisponible()))continue;Long imagen=adjuntos.findByEmpIdAndAdjModIgnoreCaseAndAdjTipRegIgnoreCaseAndAdjRegIdOrderByAdjId(empresaId,"ADMINISTRACION","MODULO",m.getId()).stream().filter(a->Boolean.TRUE.equals(a.getAdjPri())).map(Adjunto::getAdjId).findFirst().orElse(null);salida.add(new ModuloPanel(m.getId(),m.getCodigo(),m.getTitulo(),m.getDescripcion(),m.getRuta(),e.getPosicion(),e.getDisponible(),imagen));}salida.sort(Comparator.comparing(ModuloPanel::posicion).thenComparing(ModuloPanel::id));return salida;}
 private void soloAdministrador(){if(!accesos.administradorGlobal(contexto.usuarioActual()))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"El Registro y la Gestión de Módulos son exclusivos del Administrador.");}
 private void comprobarEmpresa(Long empresaId){if(empresaId==null||empresaId<=0||empresaRepository.findById(empresaId).isEmpty())throw new IllegalArgumentException("Debe seleccionar una empresa válida.");}
 private void validar(ModuloEntrada i){if(i.codigo()==null||!i.codigo().matches("[A-Z0-9_]+")||i.titulo()==null||i.titulo().isBlank()||i.descripcion()==null||i.descripcion().isBlank()||i.ruta()==null||!i.ruta().matches("[a-zA-Z0-9/-]+"))throw new IllegalArgumentException("Código, título, descripción y ruta son obligatorios.");}
 private void aplicar(ModuloAplicacion m,ModuloEntrada i,boolean nuevo){m.setCodigo(i.codigo().trim().toUpperCase());m.setTitulo(i.titulo().trim());m.setDescripcion(i.descripcion().trim());m.setRuta(i.ruta().trim());m.setPosicion(i.posicion()==null?1:Math.max(1,i.posicion()));m.setUsuario(contexto.nombreUsuario());m.setFecha(contexto.fechaActual());if(nuevo)m.setActivo(true);}
}
