package com.jbrempresa.backend.controller;
import java.math.BigInteger;import java.util.*;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.bind.annotation.*;import com.jbrempresa.backend.core.context.ContextoOperacion;import com.jbrempresa.backend.core.security.CifradoDatosSensibles;import com.jbrempresa.backend.entity.*;import com.jbrempresa.backend.repository.*;
@RestController @RequestMapping("/personas-complementos") public class PersonaComplementosController{
 private static final Set<String>TIP_REP=Set.of("LEGAL","AUTORIZADO","TUTOR","APODERADO","OTRO"),TIP_DON=Set.of("POSTAL","FISCAL","ADMINISTRATIVA","JUDICIAL","OTRA"),TIP_DOB=Set.of("CARGO","ABONO"),EST_DOB=Set.of("ACTIVA","INACTIVA");
 private final RepresentanteRepository representantes;private final DomicilioNotificacionRepository notificaciones;private final DomiciliacionBancariaRepository bancos;private final PersonaRepository personas;private final DomicilioRepository domicilios;private final ContextoOperacion contexto;private final CifradoDatosSensibles cifrado;
 public PersonaComplementosController(RepresentanteRepository a,DomicilioNotificacionRepository b,DomiciliacionBancariaRepository c,PersonaRepository d,DomicilioRepository e,ContextoOperacion f,CifradoDatosSensibles g){representantes=a;notificaciones=b;bancos=c;personas=d;domicilios=e;contexto=f;cifrado=g;}
 @GetMapping("/representantes")public List<Representante>representantes(){return representantes.findByEmpIdAndRepActTrueOrderByRepId(cli());}
 @PostMapping("/representantes")@Transactional public Representante crear(@RequestBody Representante v){v.setRepId(null);preparar(v);return representantes.save(v);}
 @PutMapping("/representantes/{id}")@Transactional public Representante actualizar(@PathVariable Long id,@RequestBody Representante v){Representante x=representantes.findByEmpIdAndRepId(cli(),id).orElseThrow(()->error("Representante no encontrado."));x.setPerId(v.getPerId());x.setRepPerId(v.getRepPerId());x.setRepTip(v.getRepTip());x.setRepFecDes(v.getRepFecDes());x.setRepFecHas(v.getRepFecHas());x.setRepPri(v.getRepPri());x.setRepObs(v.getRepObs());preparar(x);return representantes.save(x);}
 @DeleteMapping("/representantes/{id}")@Transactional public void borrarRepresentante(@PathVariable Long id){Representante x=representantes.findByEmpIdAndRepId(cli(),id).orElseThrow(()->error("Representante no encontrado."));x.setRepAct(false);mov(x);representantes.save(x);}
 @GetMapping("/domicilios-notificacion")public List<DomicilioNotificacion>notificaciones(){return notificaciones.findByEmpIdAndDonActTrueOrderByDonId(cli());}
 @PostMapping("/domicilios-notificacion")@Transactional public DomicilioNotificacion crear(@RequestBody DomicilioNotificacion v){v.setDonId(null);preparar(v);return notificaciones.save(v);}
 @PutMapping("/domicilios-notificacion/{id}")@Transactional public DomicilioNotificacion actualizar(@PathVariable Long id,@RequestBody DomicilioNotificacion v){DomicilioNotificacion x=notificaciones.findByEmpIdAndDonId(cli(),id).orElseThrow(()->error("Domicilio de notificación no encontrado."));x.setPerId(v.getPerId());x.setDomId(v.getDomId());x.setDonTip(v.getDonTip());x.setDonFecDes(v.getDonFecDes());x.setDonFecHas(v.getDonFecHas());x.setDonPri(v.getDonPri());x.setDonObs(v.getDonObs());preparar(x);return notificaciones.save(x);}
 @DeleteMapping("/domicilios-notificacion/{id}")@Transactional public void borrarNotificacion(@PathVariable Long id){DomicilioNotificacion x=notificaciones.findByEmpIdAndDonId(cli(),id).orElseThrow(()->error("Domicilio de notificación no encontrado."));x.setDonAct(false);mov(x);notificaciones.save(x);}
 @GetMapping("/domiciliaciones-bancarias")public List<DomiciliacionBancaria>bancos(){return bancos.findByEmpIdAndDobActTrueOrderByDobId(cli()).stream().peek(this::enmascarar).toList();}
 @PostMapping("/domiciliaciones-bancarias")@Transactional public DomiciliacionBancaria crear(@RequestBody DomiciliacionBancaria v){v.setDobId(null);preparar(v,null);DomiciliacionBancaria r=bancos.save(v);enmascarar(r);return r;}
 @PutMapping("/domiciliaciones-bancarias/{id}")@Transactional public DomiciliacionBancaria actualizar(@PathVariable Long id,@RequestBody DomiciliacionBancaria v){DomiciliacionBancaria x=bancos.findByEmpIdAndDobId(cli(),id).orElseThrow(()->error("Domiciliación bancaria no encontrada."));x.setPerId(v.getPerId());x.setDobTip(v.getDobTip());x.setDobTit(v.getDobTit());x.setDobBic(v.getDobBic());x.setDobRefMan(v.getDobRefMan());x.setDobFecMan(v.getDobFecMan());x.setDobPri(v.getDobPri());x.setDobEst(v.getDobEst());preparar(x,v.getDobIban());DomiciliacionBancaria r=bancos.save(x);enmascarar(r);return r;}
 @DeleteMapping("/domiciliaciones-bancarias/{id}")@Transactional public void borrarBanco(@PathVariable Long id){DomiciliacionBancaria x=bancos.findByEmpIdAndDobId(cli(),id).orElseThrow(()->error("Domiciliación bancaria no encontrada."));x.setDobAct(false);mov(x);bancos.save(x);}
 private void preparar(Representante v){persona(v.getPerId());persona(v.getRepPerId());if(v.getPerId().equals(v.getRepPerId()))throw error("Una Persona no puede representarse a sí misma.");v.setRepTip(may(v.getRepTip()));if(!TIP_REP.contains(v.getRepTip()))throw error("Tipo de representación no válido.");fechas(v.getRepFecDes(),v.getRepFecHas());v.setRepPri(Boolean.TRUE.equals(v.getRepPri()));if(v.getRepPri())representantes.findByEmpIdAndPerIdAndRepActTrue(cli(),v.getPerId()).stream().filter(x->!Objects.equals(x.getRepId(),v.getRepId())).forEach(x->{x.setRepPri(false);mov(x);representantes.save(x);});v.setEmpId(cli());v.setRepAct(true);mov(v);}
 private void preparar(DomicilioNotificacion v){persona(v.getPerId());domicilios.findByEmpIdAndDomIdAndDomActTrue(cli(),v.getDomId()).filter(x->!"B".equals(x.getDomTipMov())).orElseThrow(()->error("Domicilio no válido."));v.setDonTip(may(v.getDonTip()));if(!TIP_DON.contains(v.getDonTip()))throw error("Tipo de notificación no válido.");fechas(v.getDonFecDes(),v.getDonFecHas());v.setDonPri(Boolean.TRUE.equals(v.getDonPri()));if(v.getDonPri())notificaciones.findByEmpIdAndPerIdAndDonActTrue(cli(),v.getPerId()).stream().filter(x->!Objects.equals(x.getDonId(),v.getDonId())).forEach(x->{x.setDonPri(false);mov(x);notificaciones.save(x);});v.setEmpId(cli());v.setDonAct(true);mov(v);}
 private void preparar(DomiciliacionBancaria v,String ibanEntrada){persona(v.getPerId());v.setDobTip(may(v.getDobTip()));v.setDobEst(may(v.getDobEst()));if(!TIP_DOB.contains(v.getDobTip()))throw error("La domiciliación debe ser de CARGO o ABONO.");if(!EST_DOB.contains(v.getDobEst()))throw error("Estado bancario no válido.");if(v.getDobTit()==null||v.getDobTit().isBlank())throw error("El titular es obligatorio.");String iban=ibanEntrada==null?v.getDobIban():ibanEntrada;if(iban!=null&&!iban.isBlank()&&!iban.contains("*")){iban=iban.replaceAll("\\s","").toUpperCase();if(!ibanValido(iban))throw error("El IBAN no es válido.");v.setDobIbanCif(cifrado.cifrar(iban));}if(v.getDobIbanCif()==null)throw error("El IBAN es obligatorio.");v.setDobPri(Boolean.TRUE.equals(v.getDobPri()));if(v.getDobPri())bancos.findByEmpIdAndPerIdAndDobActTrue(cli(),v.getPerId()).stream().filter(x->v.getDobTip().equals(x.getDobTip())&&!Objects.equals(x.getDobId(),v.getDobId())).forEach(x->{x.setDobPri(false);mov(x);bancos.save(x);});v.setEmpId(cli());v.setDobAct(true);mov(v);}
 private void enmascarar(DomiciliacionBancaria v){String i=cifrado.descifrar(v.getDobIbanCif());v.setDobIban(i.length()<4?"****":"**** **** **** "+i.substring(i.length()-4));}
 private boolean ibanValido(String i){if(!i.matches("[A-Z]{2}[0-9]{2}[A-Z0-9]{11,30}"))return false;String r=i.substring(4)+i.substring(0,4),n="";for(char c:r.toCharArray())n+=Character.isDigit(c)?c:String.valueOf(c-'A'+10);return new BigInteger(n).mod(BigInteger.valueOf(97)).intValue()==1;}
 private void persona(Long id){personas.findByEmpIdAndPerIdAndPerActTrue(cli(),id).filter(x->!"B".equals(x.getPerTipMov())).orElseThrow(()->error("Persona no válida."));}private void fechas(java.time.LocalDate d,java.time.LocalDate h){if(d!=null&&h!=null&&h.isBefore(d))throw error("La fecha hasta no puede ser anterior a la fecha desde.");}private String may(String v){return v==null?"":v.trim().toUpperCase();}private Long cli(){return contexto.empresaId();}private IllegalArgumentException error(String m){return new IllegalArgumentException(m);}
 private void mov(Representante v){v.setRepUsuMov(contexto.nombreUsuario());v.setRepFecMov(contexto.fechaActual());}private void mov(DomicilioNotificacion v){v.setDonUsuMov(contexto.nombreUsuario());v.setDonFecMov(contexto.fechaActual());}private void mov(DomiciliacionBancaria v){v.setDobUsuMov(contexto.nombreUsuario());v.setDobFecMov(contexto.fechaActual());}
}
